-- =============================================================================
-- ENTITY SEED DATA WITH CROSS-SOURCE MAPPINGS
-- =============================================================================
-- This migration:
-- 1. Creates entities from Velo coins (>$1M OI) 
-- 2. Maps Velo, Artemis, AND DefiLlama source IDs to canonical entities
-- =============================================================================

BEGIN;

-- =============================================================================
-- PART 1: INSERT ENTITIES
-- =============================================================================
-- Uses ON CONFLICT DO NOTHING to be idempotent

INSERT INTO entities (canonical_id, name, symbol, entity_type, asset_class, sector)
VALUES
    ('000babydoge', '000BABYDOGE', '1000000BABYDOGE', 'token', 'crypto', 'other'),
    ('000bob', '000BOB', '1000000BOB', 'token', 'crypto', 'other'),
    ('000mog', '000MOG', '1000000MOG', 'token', 'crypto', 'other'),
    ('0g', '0G', '0G', 'token', 'crypto', 'other'),
    ('0why', '0WHY', '10000WHY', 'token', 'crypto', 'other'),
    ('1inch', '1INCH', '1INCH', 'token', 'crypto', 'other'),
    ('2z', '2Z', '2Z', 'token', 'crypto', 'other'),
    ('4', '4', '4', 'token', 'crypto', 'other'),
    ('42', '42', '42', 'token', 'crypto', 'other'),
    ('a', 'A', 'A', 'token', 'crypto', 'other'),
    ('a2z', 'A2Z', 'A2Z', 'token', 'crypto', 'other'),
    ('aave', 'Aave', 'AAVE', 'protocol', 'crypto', 'defi_lending'),
    ('ace', 'ACE', 'ACE', 'token', 'crypto', 'other'),
    ('ach', 'ACH', 'ACH', 'token', 'crypto', 'other'),
    ('act', 'ACT', 'ACT', 'token', 'crypto', 'other'),
    ('acx', 'ACX', 'ACX', 'token', 'crypto', 'other'),
    ('aergo', 'AERGO', 'AERGO', 'token', 'crypto', 'other'),
    ('aero', 'AERO', 'AERO', 'token', 'crypto', 'other'),
    ('aevo', 'AEVO', 'AEVO', 'token', 'crypto', 'other'),
    ('agi', 'AGI', 'AGI', 'token', 'crypto', 'other'),
    ('agld', 'AGLD', 'AGLD', 'token', 'crypto', 'other'),
    ('agt', 'AGT', 'AGT', 'token', 'crypto', 'other'),
    ('ai', 'AI', 'AI', 'token', 'crypto', 'other'),
    ('ain', 'AIN', 'AIN', 'token', 'crypto', 'other'),
    ('aio', 'AIO', 'AIO', 'token', 'crypto', 'other'),
    ('aiot', 'AIOT', 'AIOT', 'token', 'crypto', 'other'),
    ('aioz', 'AIOZ', 'AIOZ', 'token', 'crypto', 'other'),
    ('aixbt', 'AIXBT', 'AIXBT', 'token', 'crypto', 'other'),
    ('ake', 'AKE', 'AKE', 'token', 'crypto', 'other'),
    ('akt', 'AKT', 'AKT', 'token', 'crypto', 'other'),
    ('alch', 'ALCH', 'ALCH', 'token', 'crypto', 'other'),
    ('aleo', 'ALEO', 'ALEO', 'token', 'crypto', 'other'),
    ('algorand', 'Algorand', 'ALGO', 'chain', 'crypto', 'l1'),
    ('alice', 'ALICE', 'ALICE', 'token', 'crypto', 'other'),
    ('all', 'ALL', 'ALL', 'token', 'crypto', 'other'),
    ('allo', 'ALLO', 'ALLO', 'token', 'crypto', 'other'),
    ('alpine', 'ALPINE', 'ALPINE', 'token', 'crypto', 'other'),
    ('alt', 'ALT', 'ALT', 'token', 'crypto', 'other'),
    ('anime', 'ANIME', 'ANIME', 'token', 'crypto', 'other'),
    ('ankr', 'ANKR', 'ANKR', 'token', 'crypto', 'other'),
    ('ape', 'APE', 'APE', 'token', 'crypto', 'other'),
    ('apex', 'APEX', 'APEX', 'token', 'crypto', 'other'),
    ('api3', 'API3', 'API3', 'token', 'crypto', 'other'),
    ('apr', 'APR', 'APR', 'token', 'crypto', 'other'),
    ('aptos', 'Aptos', 'APT', 'chain', 'crypto', 'l1'),
    ('ar', 'AR', 'AR', 'token', 'crypto', 'other'),
    ('arbitrum', 'Arbitrum', 'ARB', 'chain', 'crypto', 'l2'),
    ('arc', 'ARC', 'ARC', 'token', 'crypto', 'other'),
    ('aria', 'ARIA', 'ARIA', 'token', 'crypto', 'other'),
    ('ark', 'ARK', 'ARK', 'token', 'crypto', 'other'),
    ('arkm', 'ARKM', 'ARKM', 'token', 'crypto', 'other'),
    ('arpa', 'ARPA', 'ARPA', 'token', 'crypto', 'other'),
    ('asr', 'ASR', 'ASR', 'token', 'crypto', 'other'),
    ('aster', 'ASTER', 'ASTER', 'token', 'crypto', 'other'),
    ('astr', 'ASTR', 'ASTR', 'token', 'crypto', 'other'),
    ('at', 'AT', 'AT', 'token', 'crypto', 'other'),
    ('ata', 'ATA', 'ATA', 'token', 'crypto', 'other'),
    ('ath', 'ATH', 'ATH', 'token', 'crypto', 'other'),
    ('avalanche', 'Avalanche', 'AVAX', 'chain', 'crypto', 'l1'),
    ('binance-smart-chain', 'BNB Chain', 'BNB', 'chain', 'crypto', 'l1'),
    ('bitcoin', 'Bitcoin', 'BTC', 'chain', 'crypto', 'l1'),
    ('bitcoin-cash', 'Bitcoin Cash', 'BCH', 'chain', 'crypto', 'l1'),
    ('bittensor', 'Bittensor', 'TAO', 'protocol', 'crypto', 'ai'),
    ('blast', 'BLAST', 'BLAST', 'token', 'crypto', 'other'),
    ('bless', 'BLESS', 'BLESS', 'token', 'crypto', 'other'),
    ('bluai', 'BLUAI', 'BLUAI', 'token', 'crypto', 'other'),
    ('blur', 'BLUR', 'BLUR', 'token', 'crypto', 'other'),
    ('bmt', 'BMT', 'BMT', 'token', 'crypto', 'other'),
    ('bnt', 'BNT', 'BNT', 'token', 'crypto', 'other'),
    ('bob', 'BOB', 'BOB', 'token', 'crypto', 'other'),
    ('bome', 'BOME', 'BOME', 'token', 'crypto', 'other'),
    ('bonk', 'Bonk', '1000BONK', 'token', 'crypto', 'meme'),
    ('br', 'BR', 'BR', 'token', 'crypto', 'other'),
    ('brett', 'BRETT', 'BRETT', 'token', 'crypto', 'other'),
    ('brev', 'BREV', 'BREV', 'token', 'crypto', 'other'),
    ('broccoli', 'BROCCOLI', 'BROCCOLI', 'token', 'crypto', 'other'),
    ('broccoli714', 'BROCCOLI714', 'BROCCOLI714', 'token', 'crypto', 'other'),
    ('broccolif3b', 'BROCCOLIF3B', 'BROCCOLIF3B', 'token', 'crypto', 'other'),
    ('bsu', 'BSU', 'BSU', 'token', 'crypto', 'other'),
    ('bsv', 'BSV', 'BSV', 'token', 'crypto', 'other'),
    ('btr', 'BTR', 'BTR', 'token', 'crypto', 'other'),
    ('btt', 'BTT', '1000BTT', 'token', 'crypto', 'other'),
    ('bulla', 'BULLA', 'BULLA', 'token', 'crypto', 'other'),
    ('c', 'C', 'C', 'token', 'crypto', 'other'),
    ('c98', 'C98', 'C98', 'token', 'crypto', 'other'),
    ('cake', 'CAKE', 'CAKE', 'token', 'crypto', 'other'),
    ('cardano', 'Cardano', 'ADA', 'chain', 'crypto', 'l1'),
    ('carv', 'CARV', 'CARV', 'token', 'crypto', 'other'),
    ('cat', 'CAT', '1000CAT', 'token', 'crypto', 'other'),
    ('cati', 'CATI', 'CATI', 'token', 'crypto', 'other'),
    ('cc', 'CC', 'CC', 'token', 'crypto', 'other'),
    ('celestia', 'Celestia', 'TIA', 'chain', 'crypto', 'l1'),
    ('celo', 'CELO', 'CELO', 'token', 'crypto', 'other'),
    ('celr', 'CELR', 'CELR', 'token', 'crypto', 'other'),
    ('cetus', 'CETUS', 'CETUS', 'token', 'crypto', 'other'),
    ('cfx', 'CFX', 'CFX', 'token', 'crypto', 'other'),
    ('chainlink', 'Chainlink', 'LINK', 'protocol', 'crypto', 'oracle'),
    ('cheems', 'CHEEMS', '1000CHEEMS', 'token', 'crypto', 'other'),
    ('cosmos', 'Cosmos Hub', 'ATOM', 'chain', 'crypto', 'l1'),
    ('curve', 'Curve', 'CRV', 'protocol', 'crypto', 'defi_dex'),
    ('dam', 'DAM', 'DAM', 'token', 'crypto', 'other'),
    ('dash', 'DASH', 'DASH', 'token', 'crypto', 'other'),
    ('dbr', 'DBR', 'DBR', 'token', 'crypto', 'other'),
    ('deep', 'DEEP', 'DEEP', 'token', 'crypto', 'other'),
    ('degen', 'DEGEN', 'DEGEN', 'token', 'crypto', 'other'),
    ('dego', 'DEGO', 'DEGO', 'token', 'crypto', 'other'),
    ('dent', 'DENT', 'DENT', 'token', 'crypto', 'other'),
    ('dexe', 'DEXE', 'DEXE', 'token', 'crypto', 'other'),
    ('df', 'DF', 'DF', 'token', 'crypto', 'other'),
    ('dia', 'DIA', 'DIA', 'token', 'crypto', 'other'),
    ('dodox', 'DODOX', 'DODOX', 'token', 'crypto', 'other'),
    ('dog', 'DOG', 'DOG', 'token', 'crypto', 'other'),
    ('dogecoin', 'Dogecoin', 'DOGE', 'token', 'crypto', 'meme'),
    ('dogs', 'DOGS', 'DOGS', 'token', 'crypto', 'other'),
    ('dolo', 'DOLO', 'DOLO', 'token', 'crypto', 'other'),
    ('dood', 'DOOD', 'DOOD', 'token', 'crypto', 'other'),
    ('drift', 'DRIFT', 'DRIFT', 'token', 'crypto', 'other'),
    ('dusk', 'DUSK', 'DUSK', 'token', 'crypto', 'other'),
    ('dydx', 'dYdX', 'DYDX', 'protocol', 'crypto', 'defi_derivatives'),
    ('dym', 'DYM', 'DYM', 'token', 'crypto', 'other'),
    ('eden', 'EDEN', 'EDEN', 'token', 'crypto', 'other'),
    ('edu', 'EDU', 'EDU', 'token', 'crypto', 'other'),
    ('egld', 'EGLD', 'EGLD', 'token', 'crypto', 'other'),
    ('eigenlayer', 'EigenLayer', 'EIGEN', 'protocol', 'crypto', 'restaking'),
    ('enj', 'ENJ', 'ENJ', 'token', 'crypto', 'other'),
    ('ens', 'ENS', 'ENS', 'token', 'crypto', 'other'),
    ('enso', 'ENSO', 'ENSO', 'token', 'crypto', 'other'),
    ('epic', 'EPIC', 'EPIC', 'token', 'crypto', 'other'),
    ('ept', 'EPT', 'EPT', 'token', 'crypto', 'other'),
    ('era', 'ERA', 'ERA', 'token', 'crypto', 'other'),
    ('es', 'ES', 'ES', 'token', 'crypto', 'other'),
    ('esports', 'ESPORTS', 'ESPORTS', 'token', 'crypto', 'other'),
    ('ethbtc', 'ETHBTC', 'ETHBTC', 'token', 'crypto', 'other'),
    ('ethena', 'Ethena', 'ENA', 'protocol', 'crypto', 'defi_stablecoin'),
    ('ethereum', 'Ethereum', 'ETH', 'chain', 'crypto', 'l1'),
    ('ethereum-classic', 'Ethereum Classic', 'ETC', 'chain', 'crypto', 'l1'),
    ('ethfi', 'ETHFI', 'ETHFI', 'token', 'crypto', 'other'),
    ('ethw', 'ETHW', 'ETHW', 'token', 'crypto', 'other'),
    ('eul', 'EUL', 'EUL', 'token', 'crypto', 'other'),
    ('evaa', 'EVAA', 'EVAA', 'token', 'crypto', 'other'),
    ('f', 'F', 'F', 'token', 'crypto', 'other'),
    ('fartcoin', 'Fartcoin', 'FARTCOIN', 'token', 'crypto', 'meme'),
    ('fetch-ai', 'Fetch.ai', 'FET', 'protocol', 'crypto', 'ai'),
    ('ff', 'FF', 'FF', 'token', 'crypto', 'other'),
    ('fhe', 'FHE', 'FHE', 'token', 'crypto', 'other'),
    ('fida', 'FIDA', 'FIDA', 'token', 'crypto', 'other'),
    ('filecoin', 'Filecoin', 'FIL', 'chain', 'crypto', 'l1'),
    ('fio', 'FIO', 'FIO', 'token', 'crypto', 'other'),
    ('flock', 'FLOCK', 'FLOCK', 'token', 'crypto', 'other'),
    ('floki', 'FLOKI', '1000FLOKI', 'token', 'crypto', 'meme'),
    ('flow', 'FLOW', 'FLOW', 'token', 'crypto', 'other'),
    ('flr', 'FLR', 'FLR', 'token', 'crypto', 'other'),
    ('fluid', 'FLUID', 'FLUID', 'token', 'crypto', 'other'),
    ('flux', 'FLUX', 'FLUX', 'token', 'crypto', 'other'),
    ('fogo', 'FOGO', 'FOGO', 'token', 'crypto', 'other'),
    ('folks', 'FOLKS', 'FOLKS', 'token', 'crypto', 'other'),
    ('form', 'FORM', 'FORM', 'token', 'crypto', 'other'),
    ('forth', 'FORTH', 'FORTH', 'token', 'crypto', 'other'),
    ('frax', 'FRAX', 'FRAX', 'token', 'crypto', 'other'),
    ('fun', 'FUN', 'FUN', 'token', 'crypto', 'other'),
    ('g', 'G', 'G', 'token', 'crypto', 'other'),
    ('gala', 'GALA', 'GALA', 'token', 'crypto', 'other'),
    ('gas', 'GAS', 'GAS', 'token', 'crypto', 'other'),
    ('ghst', 'GHST', 'GHST', 'token', 'crypto', 'other'),
    ('giga', 'GIGA', 'GIGA', 'token', 'crypto', 'other'),
    ('giggle', 'GIGGLE', 'GIGGLE', 'token', 'crypto', 'other'),
    ('glm', 'GLM', 'GLM', 'token', 'crypto', 'other'),
    ('gmt', 'GMT', 'GMT', 'token', 'crypto', 'other'),
    ('gmx', 'GMX', 'GMX', 'protocol', 'crypto', 'defi_derivatives'),
    ('goat', 'GOAT', 'GOAT', 'token', 'crypto', 'other'),
    ('gps', 'GPS', 'GPS', 'token', 'crypto', 'other'),
    ('grass', 'GRASS', 'GRASS', 'token', 'crypto', 'other'),
    ('griffain', 'GRIFFAIN', 'GRIFFAIN', 'token', 'crypto', 'other'),
    ('gtc', 'GTC', 'GTC', 'token', 'crypto', 'other'),
    ('gua', 'GUA', 'GUA', 'token', 'crypto', 'other'),
    ('gun', 'GUN', 'GUN', 'token', 'crypto', 'other'),
    ('h', 'H', 'H', 'token', 'crypto', 'other'),
    ('haedal', 'HAEDAL', 'HAEDAL', 'token', 'crypto', 'other'),
    ('hana', 'HANA', 'HANA', 'token', 'crypto', 'other'),
    ('hbar', 'HBAR', 'HBAR', 'token', 'crypto', 'other'),
    ('hei', 'HEI', 'HEI', 'token', 'crypto', 'other'),
    ('hemi', 'HEMI', 'HEMI', 'token', 'crypto', 'other'),
    ('hft', 'HFT', 'HFT', 'token', 'crypto', 'other'),
    ('high', 'HIGH', 'HIGH', 'token', 'crypto', 'other'),
    ('hippo', 'HIPPO', 'HIPPO', 'token', 'crypto', 'other'),
    ('hive', 'HIVE', 'HIVE', 'token', 'crypto', 'other'),
    ('hmstr', 'HMSTR', 'HMSTR', 'token', 'crypto', 'other'),
    ('hnt', 'HNT', 'HNT', 'token', 'crypto', 'other'),
    ('holo', 'HOLO', 'HOLO', 'token', 'crypto', 'other'),
    ('home', 'HOME', 'HOME', 'token', 'crypto', 'other'),
    ('hook', 'HOOK', 'HOOK', 'token', 'crypto', 'other'),
    ('hot', 'HOT', 'HOT', 'token', 'crypto', 'other'),
    ('hpos10i', 'HPOS10I', 'HPOS10I', 'token', 'crypto', 'other'),
    ('huma', 'HUMA', 'HUMA', 'token', 'crypto', 'other'),
    ('hyper', 'HYPER', 'HYPER', 'token', 'crypto', 'other'),
    ('hyperliquid', 'Hyperliquid', 'HYPE', 'protocol', 'crypto', 'defi_derivatives'),
    ('icnt', 'ICNT', 'ICNT', 'token', 'crypto', 'other'),
    ('icx', 'ICX', 'ICX', 'token', 'crypto', 'other'),
    ('id', 'ID', 'ID', 'token', 'crypto', 'other'),
    ('idol', 'IDOL', 'IDOL', 'token', 'crypto', 'other'),
    ('ilv', 'ILV', 'ILV', 'token', 'crypto', 'other'),
    ('imx', 'IMX', 'IMX', 'token', 'crypto', 'other'),
    ('in', 'IN', 'IN', 'token', 'crypto', 'other'),
    ('init', 'INIT', 'INIT', 'token', 'crypto', 'other'),
    ('injective', 'Injective', 'INJ', 'chain', 'crypto', 'l1'),
    ('internet-computer', 'Internet Computer', 'ICP', 'chain', 'crypto', 'l1'),
    ('io', 'IO', 'IO', 'token', 'crypto', 'other'),
    ('iost', 'IOST', 'IOST', 'token', 'crypto', 'other'),
    ('iota', 'IOTA', 'IOTA', 'token', 'crypto', 'other'),
    ('iotx', 'IOTX', 'IOTX', 'token', 'crypto', 'other'),
    ('ip', 'IP', 'IP', 'token', 'crypto', 'other'),
    ('ir', 'IR', 'IR', 'token', 'crypto', 'other'),
    ('irys', 'IRYS', 'IRYS', 'token', 'crypto', 'other'),
    ('jasmy', 'JASMY', 'JASMY', 'token', 'crypto', 'other'),
    ('jct', 'JCT', 'JCT', 'token', 'crypto', 'other'),
    ('jellyjelly', 'JELLYJELLY', 'JELLYJELLY', 'token', 'crypto', 'other'),
    ('joe', 'JOE', 'JOE', 'token', 'crypto', 'other'),
    ('jst', 'JST', 'JST', 'token', 'crypto', 'other'),
    ('jto', 'JTO', 'JTO', 'token', 'crypto', 'other'),
    ('jupiter', 'Jupiter', 'JUP', 'protocol', 'crypto', 'defi_aggregator'),
    ('kaia', 'KAIA', 'KAIA', 'token', 'crypto', 'other'),
    ('kaito', 'KAITO', 'KAITO', 'token', 'crypto', 'other'),
    ('kas', 'KAS', 'KAS', 'token', 'crypto', 'other'),
    ('kava', 'KAVA', 'KAVA', 'token', 'crypto', 'other'),
    ('kernel', 'KERNEL', 'KERNEL', 'token', 'crypto', 'other'),
    ('kgen', 'KGEN', 'KGEN', 'token', 'crypto', 'other'),
    ('kite', 'KITE', 'KITE', 'token', 'crypto', 'other'),
    ('kmno', 'KMNO', 'KMNO', 'token', 'crypto', 'other'),
    ('knc', 'KNC', 'KNC', 'token', 'crypto', 'other'),
    ('koma', 'KOMA', 'KOMA', 'token', 'crypto', 'other'),
    ('ksm', 'KSM', 'KSM', 'token', 'crypto', 'other'),
    ('la', 'LA', 'LA', 'token', 'crypto', 'other'),
    ('lab', 'LAB', 'LAB', 'token', 'crypto', 'other'),
    ('layer', 'LAYER', 'LAYER', 'token', 'crypto', 'other'),
    ('lido', 'Lido', 'LDO', 'protocol', 'crypto', 'liquid_staking'),
    ('light', 'LIGHT', 'LIGHT', 'token', 'crypto', 'other'),
    ('linea', 'LINEA', 'LINEA', 'token', 'crypto', 'other'),
    ('lista', 'LISTA', 'LISTA', 'token', 'crypto', 'other'),
    ('lit', 'LIT', 'LIT', 'token', 'crypto', 'other'),
    ('litecoin', 'Litecoin', 'LTC', 'chain', 'crypto', 'l1'),
    ('lpt', 'LPT', 'LPT', 'token', 'crypto', 'other'),
    ('lqty', 'LQTY', 'LQTY', 'token', 'crypto', 'other'),
    ('lrc', 'LRC', 'LRC', 'token', 'crypto', 'other'),
    ('lsk', 'LSK', 'LSK', 'token', 'crypto', 'other'),
    ('lumia', 'LUMIA', 'LUMIA', 'token', 'crypto', 'other'),
    ('luna2', 'LUNA2', 'LUNA2', 'token', 'crypto', 'other'),
    ('lunc', 'LUNC', '1000LUNC', 'token', 'crypto', 'other'),
    ('lyn', 'LYN', 'LYN', 'token', 'crypto', 'other'),
    ('m', 'M', 'M', 'token', 'crypto', 'other'),
    ('magic', 'MAGIC', 'MAGIC', 'token', 'crypto', 'other'),
    ('magma', 'MAGMA', 'MAGMA', 'token', 'crypto', 'other'),
    ('mana', 'MANA', 'MANA', 'token', 'crypto', 'other'),
    ('manta', 'MANTA', 'MANTA', 'token', 'crypto', 'other'),
    ('mask', 'MASK', 'MASK', 'token', 'crypto', 'other'),
    ('mav', 'MAV', 'MAV', 'token', 'crypto', 'other'),
    ('mavia', 'MAVIA', 'MAVIA', 'token', 'crypto', 'other'),
    ('mbox', 'MBOX', 'MBOX', 'token', 'crypto', 'other'),
    ('me', 'ME', 'ME', 'token', 'crypto', 'other'),
    ('melania', 'MELANIA', 'MELANIA', 'token', 'crypto', 'other'),
    ('meme', 'MEME', 'MEME', 'token', 'crypto', 'other'),
    ('merl', 'MERL', 'MERL', 'token', 'crypto', 'other'),
    ('met', 'MET', 'MET', 'token', 'crypto', 'other'),
    ('metis', 'METIS', 'METIS', 'token', 'crypto', 'other'),
    ('mew', 'MEW', 'MEW', 'token', 'crypto', 'other'),
    ('mina', 'MINA', 'MINA', 'token', 'crypto', 'other'),
    ('mira', 'MIRA', 'MIRA', 'token', 'crypto', 'other'),
    ('mito', 'MITO', 'MITO', 'token', 'crypto', 'other'),
    ('mln', 'MLN', 'MLN', 'token', 'crypto', 'other'),
    ('mmt', 'MMT', 'MMT', 'token', 'crypto', 'other'),
    ('mnt', 'MNT', 'MNT', 'token', 'crypto', 'other'),
    ('moca', 'MOCA', 'MOCA', 'token', 'crypto', 'other'),
    ('mon', 'MON', 'MON', 'token', 'crypto', 'other'),
    ('moodeng', 'MOODENG', 'MOODENG', 'token', 'crypto', 'other'),
    ('morpho', 'MORPHO', 'MORPHO', 'token', 'crypto', 'other'),
    ('move', 'MOVE', 'MOVE', 'token', 'crypto', 'other'),
    ('movr', 'MOVR', 'MOVR', 'token', 'crypto', 'other'),
    ('mtl', 'MTL', 'MTL', 'token', 'crypto', 'other'),
    ('mubarak', 'MUBARAK', 'MUBARAK', 'token', 'crypto', 'other'),
    ('myx', 'MYX', 'MYX', 'token', 'crypto', 'other'),
    ('naoris', 'NAORIS', 'NAORIS', 'token', 'crypto', 'other'),
    ('near', 'NEAR Protocol', 'NEAR', 'chain', 'crypto', 'l1'),
    ('neiro', 'NEIRO', 'NEIRO', 'token', 'crypto', 'other'),
    ('neirocto', 'NEIROCTO', '1000NEIROCTO', 'token', 'crypto', 'other'),
    ('neo', 'NEO', 'NEO', 'token', 'crypto', 'other'),
    ('newt', 'NEWT', 'NEWT', 'token', 'crypto', 'other'),
    ('nfp', 'NFP', 'NFP', 'token', 'crypto', 'other'),
    ('night', 'NIGHT', 'NIGHT', 'token', 'crypto', 'other'),
    ('nil', 'NIL', 'NIL', 'token', 'crypto', 'other'),
    ('nkn', 'NKN', 'NKN', 'token', 'crypto', 'other'),
    ('nmr', 'NMR', 'NMR', 'token', 'crypto', 'other'),
    ('nom', 'NOM', 'NOM', 'token', 'crypto', 'other'),
    ('not', 'NOT', 'NOT', 'token', 'crypto', 'other'),
    ('ntrn', 'NTRN', 'NTRN', 'token', 'crypto', 'other'),
    ('nxpc', 'NXPC', 'NXPC', 'token', 'crypto', 'other'),
    ('og', 'OG', 'OG', 'token', 'crypto', 'other'),
    ('ogn', 'OGN', 'OGN', 'token', 'crypto', 'other'),
    ('okb', 'OKB', 'OKB', 'token', 'crypto', 'other'),
    ('ol', 'OL', 'OL', 'token', 'crypto', 'other'),
    ('om', 'OM', 'OM', 'token', 'crypto', 'other'),
    ('on', 'ON', 'ON', 'token', 'crypto', 'other'),
    ('ondo', 'ONDO', 'ONDO', 'token', 'crypto', 'other'),
    ('one', 'ONE', 'ONE', 'token', 'crypto', 'other'),
    ('ong', 'ONG', 'ONG', 'token', 'crypto', 'other'),
    ('ont', 'ONT', 'ONT', 'token', 'crypto', 'other'),
    ('open', 'OPEN', 'OPEN', 'token', 'crypto', 'other'),
    ('optimism', 'Optimism', 'OP', 'chain', 'crypto', 'l2'),
    ('orca', 'ORCA', 'ORCA', 'token', 'crypto', 'other'),
    ('order', 'ORDER', 'ORDER', 'token', 'crypto', 'other'),
    ('ordi', 'ORDI', 'ORDI', 'token', 'crypto', 'other'),
    ('oxt', 'OXT', 'OXT', 'token', 'crypto', 'other'),
    ('parti', 'PARTI', 'PARTI', 'token', 'crypto', 'other'),
    ('paxg', 'PAXG', 'PAXG', 'token', 'crypto', 'other'),
    ('peaq', 'PEAQ', 'PEAQ', 'token', 'crypto', 'other'),
    ('pendle', 'Pendle', 'PENDLE', 'protocol', 'crypto', 'defi_yield'),
    ('pengu', 'PENGU', 'PENGU', 'token', 'crypto', 'other'),
    ('people', 'PEOPLE', 'PEOPLE', 'token', 'crypto', 'other'),
    ('pepe', 'Pepe', '1000PEPE', 'token', 'crypto', 'meme'),
    ('pha', 'PHA', 'PHA', 'token', 'crypto', 'other'),
    ('phb', 'PHB', 'PHB', 'token', 'crypto', 'other'),
    ('pieverse', 'PIEVERSE', 'PIEVERSE', 'token', 'crypto', 'other'),
    ('pippin', 'PIPPIN', 'PIPPIN', 'token', 'crypto', 'other'),
    ('pixel', 'PIXEL', 'PIXEL', 'token', 'crypto', 'other'),
    ('play', 'PLAY', 'PLAY', 'token', 'crypto', 'other'),
    ('plume', 'PLUME', 'PLUME', 'token', 'crypto', 'other'),
    ('pnut', 'PNUT', 'PNUT', 'token', 'crypto', 'other'),
    ('pol', 'POL', 'POL', 'token', 'crypto', 'other'),
    ('polkadot', 'Polkadot', 'DOT', 'chain', 'crypto', 'l1'),
    ('polyx', 'POLYX', 'POLYX', 'token', 'crypto', 'other'),
    ('ponke', 'PONKE', 'PONKE', 'token', 'crypto', 'other'),
    ('popcat', 'POPCAT', 'POPCAT', 'token', 'crypto', 'other'),
    ('portal', 'PORTAL', 'PORTAL', 'token', 'crypto', 'other'),
    ('power', 'POWER', 'POWER', 'token', 'crypto', 'other'),
    ('powr', 'POWR', 'POWR', 'token', 'crypto', 'other'),
    ('prom', 'PROM', 'PROM', 'token', 'crypto', 'other'),
    ('prompt', 'PROMPT', 'PROMPT', 'token', 'crypto', 'other'),
    ('prove', 'PROVE', 'PROVE', 'token', 'crypto', 'other'),
    ('ptb', 'PTB', 'PTB', 'token', 'crypto', 'other'),
    ('puffer', 'PUFFER', 'PUFFER', 'token', 'crypto', 'other'),
    ('pump', 'PUMP', 'PUMP', 'token', 'crypto', 'other'),
    ('pumpbtc', 'PUMPBTC', 'PUMPBTC', 'token', 'crypto', 'other'),
    ('pundix', 'PUNDIX', 'PUNDIX', 'token', 'crypto', 'other'),
    ('pyth', 'Pyth Network', 'PYTH', 'protocol', 'crypto', 'oracle'),
    ('q', 'Q', 'Q', 'token', 'crypto', 'other'),
    ('qnt', 'QNT', 'QNT', 'token', 'crypto', 'other'),
    ('qtum', 'QTUM', 'QTUM', 'token', 'crypto', 'other'),
    ('rare', 'RARE', 'RARE', 'token', 'crypto', 'other'),
    ('rats', 'RATS', '1000RATS', 'token', 'crypto', 'other'),
    ('rave', 'RAVE', 'RAVE', 'token', 'crypto', 'other'),
    ('raydium', 'RAYDIUM', 'RAYDIUM', 'token', 'crypto', 'other'),
    ('rdnt', 'RDNT', 'RDNT', 'token', 'crypto', 'other'),
    ('recall', 'RECALL', 'RECALL', 'token', 'crypto', 'other'),
    ('red', 'RED', 'RED', 'token', 'crypto', 'other'),
    ('render', 'Render', 'RENDER', 'protocol', 'crypto', 'compute'),
    ('resolv', 'RESOLV', 'RESOLV', 'token', 'crypto', 'other'),
    ('rez', 'REZ', 'REZ', 'token', 'crypto', 'other'),
    ('rif', 'RIF', 'RIF', 'token', 'crypto', 'other'),
    ('ripple', 'XRP', 'XRP', 'chain', 'crypto', 'l1'),
    ('river', 'RIVER', 'RIVER', 'token', 'crypto', 'other'),
    ('rlc', 'RLC', 'RLC', 'token', 'crypto', 'other'),
    ('rls', 'RLS', 'RLS', 'token', 'crypto', 'other'),
    ('roam', 'ROAM', 'ROAM', 'token', 'crypto', 'other'),
    ('ronin', 'RONIN', 'RONIN', 'token', 'crypto', 'other'),
    ('rose', 'ROSE', 'ROSE', 'token', 'crypto', 'other'),
    ('rpl', 'RPL', 'RPL', 'token', 'crypto', 'other'),
    ('rsr', 'RSR', 'RSR', 'token', 'crypto', 'other'),
    ('rune', 'RUNE', 'RUNE', 'token', 'crypto', 'other'),
    ('rvn', 'RVN', 'RVN', 'token', 'crypto', 'other'),
    ('s', 'S', 'S', 'token', 'crypto', 'other'),
    ('safe', 'SAFE', 'SAFE', 'token', 'crypto', 'other'),
    ('saga', 'SAGA', 'SAGA', 'token', 'crypto', 'other'),
    ('sahara', 'SAHARA', 'SAHARA', 'token', 'crypto', 'other'),
    ('sand', 'SAND', 'SAND', 'token', 'crypto', 'other'),
    ('santos', 'SANTOS', 'SANTOS', 'token', 'crypto', 'other'),
    ('sapien', 'SAPIEN', 'SAPIEN', 'token', 'crypto', 'other'),
    ('sats', 'SATS', '1000SATS', 'token', 'crypto', 'other'),
    ('sc', 'SC', 'SC', 'token', 'crypto', 'other'),
    ('scr', 'SCR', 'SCR', 'token', 'crypto', 'other'),
    ('scrt', 'SCRT', 'SCRT', 'token', 'crypto', 'other'),
    ('sei', 'Sei', 'SEI', 'chain', 'crypto', 'l1'),
    ('sent', 'SENT', 'SENT', 'token', 'crypto', 'other'),
    ('sfp', 'SFP', 'SFP', 'token', 'crypto', 'other'),
    ('shell', 'SHELL', 'SHELL', 'token', 'crypto', 'other'),
    ('shib', 'SHIB', '1000SHIB', 'token', 'crypto', 'other'),
    ('sign', 'SIGN', 'SIGN', 'token', 'crypto', 'other'),
    ('siren', 'SIREN', 'SIREN', 'token', 'crypto', 'other'),
    ('skl', 'SKL', 'SKL', 'token', 'crypto', 'other'),
    ('sky', 'SKY', 'SKY', 'token', 'crypto', 'other'),
    ('skyai', 'SKYAI', 'SKYAI', 'token', 'crypto', 'other'),
    ('slp', 'SLP', 'SLP', 'token', 'crypto', 'other'),
    ('snt', 'SNT', 'SNT', 'token', 'crypto', 'other'),
    ('solana', 'Solana', 'SOL', 'chain', 'crypto', 'l1'),
    ('solv', 'SOLV', 'SOLV', 'token', 'crypto', 'other'),
    ('somi', 'SOMI', 'SOMI', 'token', 'crypto', 'other'),
    ('sonic', 'SONIC', 'SONIC', 'token', 'crypto', 'other'),
    ('soon', 'SOON', 'SOON', 'token', 'crypto', 'other'),
    ('soph', 'SOPH', 'SOPH', 'token', 'crypto', 'other'),
    ('soso', 'SOSO', 'SOSO', 'token', 'crypto', 'other'),
    ('spell', 'SPELL', 'SPELL', 'token', 'crypto', 'other'),
    ('spk', 'SPK', 'SPK', 'token', 'crypto', 'other'),
    ('sportfun', 'SPORTFUN', 'SPORTFUN', 'token', 'crypto', 'other'),
    ('spx', 'SPX', 'SPX', 'token', 'crypto', 'other'),
    ('sqd', 'SQD', 'SQD', 'token', 'crypto', 'other'),
    ('ssv', 'SSV', 'SSV', 'token', 'crypto', 'other'),
    ('stable', 'STABLE', 'STABLE', 'token', 'crypto', 'other'),
    ('starknet', 'Starknet', 'STRK', 'chain', 'crypto', 'l2'),
    ('stbl', 'STBL', 'STBL', 'token', 'crypto', 'other'),
    ('steem', 'STEEM', 'STEEM', 'token', 'crypto', 'other'),
    ('stg', 'STG', 'STG', 'token', 'crypto', 'other'),
    ('sto', 'STO', 'STO', 'token', 'crypto', 'other'),
    ('storj', 'STORJ', 'STORJ', 'token', 'crypto', 'other'),
    ('stx', 'STX', 'STX', 'token', 'crypto', 'other'),
    ('sui', 'Sui', 'SUI', 'chain', 'crypto', 'l1'),
    ('sun', 'SUN', 'SUN', 'token', 'crypto', 'other'),
    ('super', 'SUPER', 'SUPER', 'token', 'crypto', 'other'),
    ('sushi', 'SUSHI', 'SUSHI', 'token', 'crypto', 'other'),
    ('swarms', 'SWARMS', 'SWARMS', 'token', 'crypto', 'other'),
    ('sxp', 'SXP', 'SXP', 'token', 'crypto', 'other'),
    ('sxt', 'SXT', 'SXT', 'token', 'crypto', 'other'),
    ('syn', 'SYN', 'SYN', 'token', 'crypto', 'other'),
    ('synthetix', 'Synthetix', 'SNX', 'protocol', 'crypto', 'defi_derivatives'),
    ('syrup', 'SYRUP', 'SYRUP', 'token', 'crypto', 'other'),
    ('sys', 'SYS', 'SYS', 'token', 'crypto', 'other'),
    ('t', 'T', 'T', 'token', 'crypto', 'other'),
    ('ta', 'TA', 'TA', 'token', 'crypto', 'other'),
    ('tac', 'TAC', 'TAC', 'token', 'crypto', 'other'),
    ('tag', 'TAG', 'TAG', 'token', 'crypto', 'other'),
    ('taiko', 'TAIKO', 'TAIKO', 'token', 'crypto', 'other'),
    ('take', 'TAKE', 'TAKE', 'token', 'crypto', 'other'),
    ('tanssi', 'TANSSI', 'TANSSI', 'token', 'crypto', 'other'),
    ('the', 'THE', 'THE', 'token', 'crypto', 'other'),
    ('the-graph', 'The Graph', 'GRT', 'protocol', 'crypto', 'indexing'),
    ('theta', 'THETA', 'THETA', 'token', 'crypto', 'other'),
    ('tlm', 'TLM', 'TLM', 'token', 'crypto', 'other'),
    ('tnsr', 'TNSR', 'TNSR', 'token', 'crypto', 'other'),
    ('toncoin', 'Toncoin', 'TON', 'chain', 'crypto', 'l1'),
    ('toshi', 'TOSHI', 'TOSHI', 'token', 'crypto', 'other'),
    ('towns', 'TOWNS', 'TOWNS', 'token', 'crypto', 'other'),
    ('tradoor', 'TRADOOR', 'TRADOOR', 'token', 'crypto', 'other'),
    ('trb', 'TRB', 'TRB', 'token', 'crypto', 'other'),
    ('tree', 'TREE', 'TREE', 'token', 'crypto', 'other'),
    ('tron', 'TRON', 'TRX', 'chain', 'crypto', 'l1'),
    ('tru', 'TRU', 'TRU', 'token', 'crypto', 'other'),
    ('trump', 'Trump', 'TRUMP', 'token', 'crypto', 'meme'),
    ('trust', 'TRUST', 'TRUST', 'token', 'crypto', 'other'),
    ('truth', 'TRUTH', 'TRUTH', 'token', 'crypto', 'other'),
    ('tst', 'TST', 'TST', 'token', 'crypto', 'other'),
    ('turbo', 'TURBO', '1000TURBO', 'token', 'crypto', 'other'),
    ('turtle', 'TURTLE', 'TURTLE', 'token', 'crypto', 'other'),
    ('tut', 'TUT', 'TUT', 'token', 'crypto', 'other'),
    ('twt', 'TWT', 'TWT', 'token', 'crypto', 'other'),
    ('uai', 'UAI', 'UAI', 'token', 'crypto', 'other'),
    ('ub', 'UB', 'UB', 'token', 'crypto', 'other'),
    ('uma', 'UMA', 'UMA', 'token', 'crypto', 'other'),
    ('uniswap', 'Uniswap', 'UNI', 'protocol', 'crypto', 'defi_dex'),
    ('us', 'US', 'US', 'token', 'crypto', 'other'),
    ('usd1', 'USD1', 'USD1', 'token', 'crypto', 'other'),
    ('usdc', 'USDC', 'USDC', 'token', 'crypto', 'other'),
    ('usde', 'USDE', 'USDE', 'token', 'crypto', 'other'),
    ('useless', 'USELESS', 'USELESS', 'token', 'crypto', 'other'),
    ('ustc', 'USTC', 'USTC', 'token', 'crypto', 'other'),
    ('usual', 'USUAL', 'USUAL', 'token', 'crypto', 'other'),
    ('vana', 'VANA', 'VANA', 'token', 'crypto', 'other'),
    ('vanry', 'VANRY', 'VANRY', 'token', 'crypto', 'other'),
    ('velo', 'VELO', 'VELO', 'token', 'crypto', 'other'),
    ('velodrome', 'VELODROME', 'VELODROME', 'token', 'crypto', 'other'),
    ('velvet', 'VELVET', 'VELVET', 'token', 'crypto', 'other'),
    ('vet', 'VET', 'VET', 'token', 'crypto', 'other'),
    ('vfy', 'VFY', 'VFY', 'token', 'crypto', 'other'),
    ('vic', 'VIC', 'VIC', 'token', 'crypto', 'other'),
    ('vine', 'VINE', 'VINE', 'token', 'crypto', 'other'),
    ('virtual', 'VIRTUAL', 'VIRTUAL', 'token', 'crypto', 'other'),
    ('vtho', 'VTHO', 'VTHO', 'token', 'crypto', 'other'),
    ('vvv', 'VVV', 'VVV', 'token', 'crypto', 'other'),
    ('w', 'W', 'W', 'token', 'crypto', 'other'),
    ('wal', 'WAL', 'WAL', 'token', 'crypto', 'other'),
    ('waves', 'WAVES', 'WAVES', 'token', 'crypto', 'other'),
    ('waxp', 'WAXP', 'WAXP', 'token', 'crypto', 'other'),
    ('wct', 'WCT', 'WCT', 'token', 'crypto', 'other'),
    ('wld', 'WLD', 'WLD', 'token', 'crypto', 'other'),
    ('xec', 'XEC', '1000XEC', 'token', 'crypto', 'other')
ON CONFLICT (canonical_id) DO NOTHING;

-- =============================================================================
-- PART 2: VELO SOURCE ID MAPPINGS
-- =============================================================================

INSERT INTO entity_source_ids (entity_id, source, source_id, source_id_type)
SELECT e.entity_id, 'velo', e.symbol, 'coin'
FROM entities e
WHERE e.asset_class = 'crypto'
ON CONFLICT (source, source_id) DO NOTHING;

-- =============================================================================
-- PART 3: ARTEMIS SOURCE ID MAPPINGS
-- =============================================================================
-- Maps Artemis short IDs (btc, eth, sol) to canonical entities

INSERT INTO entity_source_ids (entity_id, source, source_id, source_id_type)
VALUES
    ((SELECT entity_id FROM entities WHERE canonical_id = 'aave'), 'artemis', 'aave', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'acx'), 'artemis', 'acx', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'aero'), 'artemis', 'aero', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'aevo'), 'artemis', 'aevo', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'aioz'), 'artemis', 'aioz', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'akt'), 'artemis', 'akt', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'aleo'), 'artemis', 'aleo', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'algorand'), 'artemis', 'algo', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'apex'), 'artemis', 'apex', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'aptos'), 'artemis', 'apt', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'ar'), 'artemis', 'ar', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'arbitrum'), 'artemis', 'arb', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'aster'), 'artemis', 'aster', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'astr'), 'artemis', 'astr', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'ath'), 'artemis', 'ath', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'avalanche'), 'artemis', 'avax', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'binance-smart-chain'), 'artemis', 'bnb', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'bitcoin'), 'artemis', 'btc', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'bitcoin-cash'), 'artemis', 'bch', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'bittensor'), 'artemis', 'tao', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'blast'), 'artemis', 'blast', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'blur'), 'artemis', 'blur', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'bob'), 'artemis', 'bob', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'bonk'), 'artemis', 'bonk', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'brett'), 'artemis', 'brett', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'btt'), 'artemis', 'btt', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'cake'), 'artemis', 'cake', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'cardano'), 'artemis', 'ada', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'celestia'), 'artemis', 'tia', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'celo'), 'artemis', 'celo', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'cetus'), 'artemis', 'cetus', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'cfx'), 'artemis', 'cfx', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'chainlink'), 'artemis', 'link', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'cosmos'), 'artemis', 'atom', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'curve'), 'artemis', 'crv', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'dbr'), 'artemis', 'dbr', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'deep'), 'artemis', 'deep', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'dogecoin'), 'artemis', 'doge', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'drift'), 'artemis', 'drift', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'dydx'), 'artemis', 'dydx', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'egld'), 'artemis', 'egld', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'eigenlayer'), 'artemis', 'eigen', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'ethena'), 'artemis', 'ena', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'ethereum'), 'artemis', 'eth', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'ethereum-classic'), 'artemis', 'etc', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'ethfi'), 'artemis', 'ethfi', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'eul'), 'artemis', 'eul', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'fartcoin'), 'artemis', 'fartcoin', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'fetch-ai'), 'artemis', 'fet', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'filecoin'), 'artemis', 'fil', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'floki'), 'artemis', 'floki', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'flow'), 'artemis', 'flow', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'flr'), 'artemis', 'flr', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'fluid'), 'artemis', 'fluid', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'gmx'), 'artemis', 'gmx', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'grass'), 'artemis', 'grass', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'hbar'), 'artemis', 'hbar', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'hnt'), 'artemis', 'hnt', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'hyperliquid'), 'artemis', 'hype', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'injective'), 'artemis', 'inj', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'internet-computer'), 'artemis', 'icp', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'iotx'), 'artemis', 'iotx', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'ip'), 'artemis', 'ip', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'joe'), 'artemis', 'joe', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'jto'), 'artemis', 'jto', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'jupiter'), 'artemis', 'jup', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'kava'), 'artemis', 'kava', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'kmno'), 'artemis', 'kmno', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'layer'), 'artemis', 'layer', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'lido'), 'artemis', 'ldo', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'light'), 'artemis', 'light', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'linea'), 'artemis', 'linea', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'litecoin'), 'artemis', 'ltc', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'lpt'), 'artemis', 'lpt', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'lqty'), 'artemis', 'lqty', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'lsk'), 'artemis', 'lsk', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'lunc'), 'artemis', 'lunc', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'manta'), 'artemis', 'manta', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'met'), 'artemis', 'met', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'metis'), 'artemis', 'metis', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'mnt'), 'artemis', 'mnt', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'mon'), 'artemis', 'mon', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'morpho'), 'artemis', 'morpho', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'move'), 'artemis', 'move', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'movr'), 'artemis', 'movr', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'near'), 'artemis', 'near', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'neo'), 'artemis', 'neo', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'okb'), 'artemis', 'okb', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'ondo'), 'artemis', 'ondo', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'optimism'), 'artemis', 'op', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'orca'), 'artemis', 'orca', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'paxg'), 'artemis', 'paxg', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'pendle'), 'artemis', 'pendle', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'pengu'), 'artemis', 'pengu', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'pepe'), 'artemis', 'pepe', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'plume'), 'artemis', 'plume', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'pol'), 'artemis', 'pol', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'polkadot'), 'artemis', 'dot', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'pump'), 'artemis', 'pump', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'pyth'), 'artemis', 'pyth', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'red'), 'artemis', 'red', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'render'), 'artemis', 'render', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'ripple'), 'artemis', 'xrp', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'rose'), 'artemis', 'rose', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'rpl'), 'artemis', 'rpl', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'rsr'), 'artemis', 'rsr', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 's'), 'artemis', 's', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'safe'), 'artemis', 'safe', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'sei'), 'artemis', 'sei', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'shib'), 'artemis', 'shib', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'sky'), 'artemis', 'sky', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'solana'), 'artemis', 'sol', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'spk'), 'artemis', 'spk', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'starknet'), 'artemis', 'strk', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'stg'), 'artemis', 'stg', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'stx'), 'artemis', 'stx', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'sui'), 'artemis', 'sui', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'synthetix'), 'artemis', 'snx', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'syrup'), 'artemis', 'syrup', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'the-graph'), 'artemis', 'grt', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'toncoin'), 'artemis', 'ton', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'tron'), 'artemis', 'trx', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'turbo'), 'artemis', 'turbo', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'uniswap'), 'artemis', 'uni', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'usd1'), 'artemis', 'usd1', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'usdc'), 'artemis', 'usdc', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'usde'), 'artemis', 'usde', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'usual'), 'artemis', 'usual', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'vet'), 'artemis', 'vet', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'virtual'), 'artemis', 'virtual', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'w'), 'artemis', 'w', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'wal'), 'artemis', 'wal', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'wld'), 'artemis', 'wld', 'ticker'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'xec'), 'artemis', 'xec', 'ticker')
ON CONFLICT (source, source_id) DO NOTHING;

-- =============================================================================
-- PART 4: DEFILLAMA SOURCE ID MAPPINGS
-- =============================================================================
-- Maps DefiLlama slugs to canonical entities

INSERT INTO entity_source_ids (entity_id, source, source_id, source_id_type)
VALUES
    ((SELECT entity_id FROM entities WHERE canonical_id = 'aave'), 'defillama', 'aave', 'slug'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'algorand'), 'defillama', 'algorand', 'slug'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'ankr'), 'defillama', 'ankr', 'slug'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'aptos'), 'defillama', 'aptos', 'slug'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'arbitrum'), 'defillama', 'arbitrum', 'slug'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'avalanche'), 'defillama', 'avalanche', 'slug'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'binance-smart-chain'), 'defillama', 'bsc', 'slug'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'bitcoin'), 'defillama', 'bitcoin', 'slug'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'cosmos'), 'defillama', 'cosmos', 'slug'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'curve'), 'defillama', 'curve-dex', 'slug'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'dogecoin'), 'defillama', 'doge', 'slug'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'dydx'), 'defillama', 'dydx', 'slug'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'eigenlayer'), 'defillama', 'eigencloud', 'slug'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'ethena'), 'defillama', 'ethena', 'slug'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'ethereum'), 'defillama', 'ethereum', 'slug'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'filecoin'), 'defillama', 'filecoin', 'slug'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'gala'), 'defillama', 'gala', 'slug'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'gmx'), 'defillama', 'gmx', 'slug'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'hyperliquid'), 'defillama', 'hyperliquid-l1', 'slug'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'injective'), 'defillama', 'injective', 'slug'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'iota'), 'defillama', 'iota', 'slug'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'jupiter'), 'defillama', 'jupiter', 'slug'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'kaia'), 'defillama', 'kaia', 'slug'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'lido'), 'defillama', 'lido', 'slug'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'litecoin'), 'defillama', 'litecoin', 'slug'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'near'), 'defillama', 'near', 'slug'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'optimism'), 'defillama', 'optimism', 'slug'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'pendle'), 'defillama', 'pendle', 'slug'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'polkadot'), 'defillama', 'polkadot', 'slug'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'portal'), 'defillama', 'portal', 'slug'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'pumpbtc'), 'defillama', 'pumpbtc', 'slug'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'resolv'), 'defillama', 'resolv', 'slug'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'ronin'), 'defillama', 'ronin', 'slug'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'saga'), 'defillama', 'saga', 'slug'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'sei'), 'defillama', 'sei', 'slug'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'solana'), 'defillama', 'solana', 'slug'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'sonic'), 'defillama', 'sonic', 'slug'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'starknet'), 'defillama', 'starknet', 'slug'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'sui'), 'defillama', 'sui', 'slug'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'synthetix'), 'defillama', 'synthetix', 'slug'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'tron'), 'defillama', 'tron', 'slug'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'uniswap'), 'defillama', 'uniswap', 'slug'),
    ((SELECT entity_id FROM entities WHERE canonical_id = 'waves'), 'defillama', 'waves', 'slug')
ON CONFLICT (source, source_id) DO NOTHING;

COMMIT;

-- =============================================================================
-- VERIFICATION QUERIES
-- =============================================================================
-- SELECT source, COUNT(*) FROM entity_source_ids GROUP BY source;
-- SELECT e.canonical_id, esi.source, esi.source_id 
-- FROM entities e 
-- JOIN entity_source_ids esi ON e.entity_id = esi.entity_id 
-- WHERE e.canonical_id = 'bitcoin';
