-- Entity seed data

INSERT INTO entities (canonical_id, name, symbol, entity_type, sector) VALUES
  ('000babydoge', '000BABYDOGE', '1000000BABYDOGE', 'token', 'other'),
  ('000bob', '000BOB', '1000000BOB', 'token', 'other'),
  ('000mog', '000MOG', '1000000MOG', 'token', 'other'),
  ('0g', '0G', '0G', 'token', 'other'),
  ('0why', '0WHY', '10000WHY', 'token', 'other'),
  ('1inch', '1INCH', '1INCH', 'token', 'other'),
  ('2z', '2Z', '2Z', 'token', 'other'),
  ('4', '4', '4', 'token', 'other'),
  ('42', '42', '42', 'token', 'other'),
  ('a', 'A', 'A', 'token', 'other'),
  ('a2z', 'A2Z', 'A2Z', 'token', 'other'),
  ('aave', 'Aave', 'AAVE', 'protocol', 'defi_lending'),
  ('ace', 'ACE', 'ACE', 'token', 'other'),
  ('ach', 'ACH', 'ACH', 'token', 'other'),
  ('act', 'ACT', 'ACT', 'token', 'other'),
  ('aergo', 'AERGO', 'AERGO', 'token', 'other'),
  ('aero', 'AERO', 'AERO', 'token', 'other'),
  ('aevo', 'AEVO', 'AEVO', 'token', 'other'),
  ('agi', 'AGI', 'AGI', 'token', 'other'),
  ('agld', 'AGLD', 'AGLD', 'token', 'other'),
  ('agt', 'AGT', 'AGT', 'token', 'other'),
  ('ai', 'AI', 'AI', 'token', 'other'),
  ('ain', 'AIN', 'AIN', 'token', 'other'),
  ('aio', 'AIO', 'AIO', 'token', 'other'),
  ('aiot', 'AIOT', 'AIOT', 'token', 'other'),
  ('aioz', 'AIOZ', 'AIOZ', 'token', 'other'),
  ('aixbt', 'AIXBT', 'AIXBT', 'token', 'other'),
  ('ake', 'AKE', 'AKE', 'token', 'other'),
  ('akt', 'AKT', 'AKT', 'token', 'other'),
  ('alch', 'ALCH', 'ALCH', 'token', 'other'),
  ('aleo', 'ALEO', 'ALEO', 'token', 'other'),
  ('algorand', 'Algorand', 'ALGO', 'chain', 'l1'),
  ('alice', 'ALICE', 'ALICE', 'token', 'other'),
  ('all', 'ALL', 'ALL', 'token', 'other'),
  ('allo', 'ALLO', 'ALLO', 'token', 'other'),
  ('alpine', 'ALPINE', 'ALPINE', 'token', 'other'),
  ('anime', 'ANIME', 'ANIME', 'token', 'other'),
  ('ankr', 'ANKR', 'ANKR', 'token', 'other'),
  ('ape', 'APE', 'APE', 'token', 'other'),
  ('apex', 'APEX', 'APEX', 'token', 'other'),
  ('api3', 'API3', 'API3', 'token', 'other'),
  ('apr', 'APR', 'APR', 'token', 'other'),
  ('aptos', 'Aptos', 'APT', 'chain', 'l1'),
  ('ar', 'AR', 'AR', 'token', 'other'),
  ('arbitrum', 'Arbitrum', 'ARB', 'chain', 'l2'),
  ('arc', 'ARC', 'ARC', 'token', 'other'),
  ('aria', 'ARIA', 'ARIA', 'token', 'other'),
  ('ark', 'ARK', 'ARK', 'token', 'other'),
  ('arpa', 'ARPA', 'ARPA', 'token', 'other'),
  ('asr', 'ASR', 'ASR', 'token', 'other'),
  ('aster', 'ASTER', 'ASTER', 'token', 'other'),
  ('astr', 'ASTR', 'ASTR', 'token', 'other'),
  ('at', 'AT', 'AT', 'token', 'other'),
  ('ata', 'ATA', 'ATA', 'token', 'other'),
  ('ath', 'ATH', 'ATH', 'token', 'other'),
  ('avalanche', 'Avalanche', 'AVAX', 'chain', 'l1'),
  ('binance-smart-chain', 'BNB Chain', 'BNB', 'chain', 'l1'),
  ('bitcoin', 'Bitcoin', 'BTC', 'chain', 'l1'),
  ('bitcoin-cash', 'Bitcoin Cash', 'BCH', 'chain', 'l1'),
  ('bittensor', 'Bittensor', 'TAO', 'protocol', 'ai'),
  ('blast', 'BLAST', 'BLAST', 'token', 'other'),
  ('bless', 'BLESS', 'BLESS', 'token', 'other'),
  ('bluai', 'BLUAI', 'BLUAI', 'token', 'other'),
  ('blur', 'BLUR', 'BLUR', 'token', 'other'),
  ('bmt', 'BMT', 'BMT', 'token', 'other'),
  ('bnt', 'BNT', 'BNT', 'token', 'other'),
  ('bob', 'BOB', 'BOB', 'token', 'other'),
  ('bome', 'BOME', 'BOME', 'token', 'other'),
  ('bonk', 'Bonk', '1000BONK', 'token', 'meme'),
  ('br', 'BR', 'BR', 'token', 'other'),
  ('brett', 'BRETT', 'BRETT', 'token', 'other'),
  ('brev', 'BREV', 'BREV', 'token', 'other'),
  ('broccoli', 'BROCCOLI', 'BROCCOLI', 'token', 'other'),
  ('broccoli714', 'BROCCOLI714', 'BROCCOLI714', 'token', 'other'),
  ('broccolif3b', 'BROCCOLIF3B', 'BROCCOLIF3B', 'token', 'other'),
  ('bsu', 'BSU', 'BSU', 'token', 'other'),
  ('bsv', 'BSV', 'BSV', 'token', 'other'),
  ('btr', 'BTR', 'BTR', 'token', 'other'),
  ('btt', 'BTT', '1000BTT', 'token', 'other'),
  ('bulla', 'BULLA', 'BULLA', 'token', 'other'),
  ('c', 'C', 'C', 'token', 'other'),
  ('c98', 'C98', 'C98', 'token', 'other'),
  ('cake', 'CAKE', 'CAKE', 'token', 'other'),
  ('cardano', 'Cardano', 'ADA', 'chain', 'l1'),
  ('carv', 'CARV', 'CARV', 'token', 'other'),
  ('cat', 'CAT', '1000CAT', 'token', 'other'),
  ('cati', 'CATI', 'CATI', 'token', 'other'),
  ('cc', 'CC', 'CC', 'token', 'other'),
  ('celestia', 'Celestia', 'TIA', 'chain', 'l1'),
  ('celo', 'CELO', 'CELO', 'token', 'other'),
  ('celr', 'CELR', 'CELR', 'token', 'other'),
  ('cetus', 'CETUS', 'CETUS', 'token', 'other'),
  ('cfx', 'CFX', 'CFX', 'token', 'other'),
  ('chainlink', 'Chainlink', 'LINK', 'protocol', 'oracle'),
  ('cheems', 'CHEEMS', '1000CHEEMS', 'token', 'other'),
  ('cosmos', 'Cosmos Hub', 'ATOM', 'chain', 'l1'),
  ('curve', 'Curve', 'CRV', 'protocol', 'defi_dex'),
  ('dam', 'DAM', 'DAM', 'token', 'other'),
  ('dash', 'DASH', 'DASH', 'token', 'other'),
  ('deep', 'DEEP', 'DEEP', 'token', 'other'),
  ('degen', 'DEGEN', 'DEGEN', 'token', 'other'),
  ('dego', 'DEGO', 'DEGO', 'token', 'other'),
  ('dent', 'DENT', 'DENT', 'token', 'other'),
  ('dexe', 'DEXE', 'DEXE', 'token', 'other'),
  ('df', 'DF', 'DF', 'token', 'other'),
  ('dia', 'DIA', 'DIA', 'token', 'other'),
  ('dodox', 'DODOX', 'DODOX', 'token', 'other'),
  ('dog', 'DOG', 'DOG', 'token', 'other'),
  ('dogecoin', 'Dogecoin', 'DOGE', 'token', 'meme'),
  ('dogs', 'DOGS', 'DOGS', 'token', 'other'),
  ('dolo', 'DOLO', 'DOLO', 'token', 'other'),
  ('dood', 'DOOD', 'DOOD', 'token', 'other'),
  ('drift', 'DRIFT', 'DRIFT', 'token', 'other'),
  ('dusk', 'DUSK', 'DUSK', 'token', 'other'),
  ('dydx', 'dYdX', 'DYDX', 'protocol', 'defi_derivatives'),
  ('dym', 'DYM', 'DYM', 'token', 'other'),
  ('eden', 'EDEN', 'EDEN', 'token', 'other'),
  ('edu', 'EDU', 'EDU', 'token', 'other'),
  ('egld', 'EGLD', 'EGLD', 'token', 'other'),
  ('eigenlayer', 'EigenLayer', 'EIGEN', 'protocol', 'restaking'),
  ('enj', 'ENJ', 'ENJ', 'token', 'other'),
  ('ens', 'ENS', 'ENS', 'token', 'other'),
  ('enso', 'ENSO', 'ENSO', 'token', 'other'),
  ('epic', 'EPIC', 'EPIC', 'token', 'other'),
  ('ept', 'EPT', 'EPT', 'token', 'other'),
  ('era', 'ERA', 'ERA', 'token', 'other'),
  ('es', 'ES', 'ES', 'token', 'other'),
  ('esports', 'ESPORTS', 'ESPORTS', 'token', 'other'),
  ('ethbtc', 'ETHBTC', 'ETHBTC', 'token', 'other'),
  ('ethena', 'Ethena', 'ENA', 'protocol', 'defi_stablecoin'),
  ('ethereum', 'Ethereum', 'ETH', 'chain', 'l1'),
  ('ethereum-classic', 'Ethereum Classic', 'ETC', 'chain', 'l1'),
  ('ethfi', 'ETHFI', 'ETHFI', 'token', 'other'),
  ('ethw', 'ETHW', 'ETHW', 'token', 'other'),
  ('eul', 'EUL', 'EUL', 'token', 'other'),
  ('evaa', 'EVAA', 'EVAA', 'token', 'other'),
  ('f', 'F', 'F', 'token', 'other'),
  ('fartcoin', 'Fartcoin', 'FARTCOIN', 'token', 'meme'),
  ('fetch-ai', 'Fetch.ai', 'FET', 'protocol', 'ai'),
  ('ff', 'FF', 'FF', 'token', 'other'),
  ('fhe', 'FHE', 'FHE', 'token', 'other'),
  ('fida', 'FIDA', 'FIDA', 'token', 'other'),
  ('filecoin', 'Filecoin', 'FIL', 'chain', 'l1'),
  ('fio', 'FIO', 'FIO', 'token', 'other'),
  ('flock', 'FLOCK', 'FLOCK', 'token', 'other'),
  ('floki', 'FLOKI', '1000FLOKI', 'token', 'meme'),
  ('flow', 'FLOW', 'FLOW', 'token', 'other'),
  ('flr', 'FLR', 'FLR', 'token', 'other'),
  ('fluid', 'FLUID', 'FLUID', 'token', 'other'),
  ('flux', 'FLUX', 'FLUX', 'token', 'other'),
  ('fogo', 'FOGO', 'FOGO', 'token', 'other'),
  ('folks', 'FOLKS', 'FOLKS', 'token', 'other'),
  ('form', 'FORM', 'FORM', 'token', 'other'),
  ('forth', 'FORTH', 'FORTH', 'token', 'other'),
  ('frax', 'FRAX', 'FRAX', 'token', 'other'),
  ('fun', 'FUN', 'FUN', 'token', 'other'),
  ('g', 'G', 'G', 'token', 'other'),
  ('gala', 'GALA', 'GALA', 'token', 'other'),
  ('gas', 'GAS', 'GAS', 'token', 'other'),
  ('ghst', 'GHST', 'GHST', 'token', 'other'),
  ('giga', 'GIGA', 'GIGA', 'token', 'other'),
  ('giggle', 'GIGGLE', 'GIGGLE', 'token', 'other'),
  ('glm', 'GLM', 'GLM', 'token', 'other'),
  ('gmt', 'GMT', 'GMT', 'token', 'other'),
  ('gmx', 'GMX', 'GMX', 'protocol', 'defi_derivatives'),
  ('goat', 'GOAT', 'GOAT', 'token', 'other'),
  ('gps', 'GPS', 'GPS', 'token', 'other'),
  ('grass', 'GRASS', 'GRASS', 'token', 'other'),
  ('griffain', 'GRIFFAIN', 'GRIFFAIN', 'token', 'other'),
  ('gtc', 'GTC', 'GTC', 'token', 'other'),
  ('gua', 'GUA', 'GUA', 'token', 'other'),
  ('gun', 'GUN', 'GUN', 'token', 'other'),
  ('h', 'H', 'H', 'token', 'other'),
  ('haedal', 'HAEDAL', 'HAEDAL', 'token', 'other'),
  ('hana', 'HANA', 'HANA', 'token', 'other'),
  ('hbar', 'HBAR', 'HBAR', 'token', 'other'),
  ('hei', 'HEI', 'HEI', 'token', 'other'),
  ('hemi', 'HEMI', 'HEMI', 'token', 'other'),
  ('hft', 'HFT', 'HFT', 'token', 'other'),
  ('high', 'HIGH', 'HIGH', 'token', 'other'),
  ('hippo', 'HIPPO', 'HIPPO', 'token', 'other'),
  ('hive', 'HIVE', 'HIVE', 'token', 'other'),
  ('hmstr', 'HMSTR', 'HMSTR', 'token', 'other'),
  ('holo', 'HOLO', 'HOLO', 'token', 'other'),
  ('home', 'HOME', 'HOME', 'token', 'other'),
  ('hook', 'HOOK', 'HOOK', 'token', 'other'),
  ('hot', 'HOT', 'HOT', 'token', 'other'),
  ('hpos10i', 'HPOS10I', 'HPOS10I', 'token', 'other'),
  ('huma', 'HUMA', 'HUMA', 'token', 'other'),
  ('hyper', 'HYPER', 'HYPER', 'token', 'other'),
  ('hyperliquid', 'Hyperliquid', 'HYPE', 'protocol', 'defi_derivatives'),
  ('icnt', 'ICNT', 'ICNT', 'token', 'other'),
  ('icx', 'ICX', 'ICX', 'token', 'other'),
  ('id', 'ID', 'ID', 'token', 'other'),
  ('idol', 'IDOL', 'IDOL', 'token', 'other'),
  ('ilv', 'ILV', 'ILV', 'token', 'other'),
  ('imx', 'IMX', 'IMX', 'token', 'other'),
  ('in', 'IN', 'IN', 'token', 'other'),
  ('init', 'INIT', 'INIT', 'token', 'other'),
  ('injective', 'Injective', 'INJ', 'chain', 'l1'),
  ('internet-computer', 'Internet Computer', 'ICP', 'chain', 'l1'),
  ('io', 'IO', 'IO', 'token', 'other'),
  ('iost', 'IOST', 'IOST', 'token', 'other'),
  ('iota', 'IOTA', 'IOTA', 'token', 'other'),
  ('iotx', 'IOTX', 'IOTX', 'token', 'other'),
  ('ip', 'IP', 'IP', 'token', 'other'),
  ('ir', 'IR', 'IR', 'token', 'other'),
  ('irys', 'IRYS', 'IRYS', 'token', 'other'),
  ('jasmy', 'JASMY', 'JASMY', 'token', 'other'),
  ('jct', 'JCT', 'JCT', 'token', 'other'),
  ('jellyjelly', 'JELLYJELLY', 'JELLYJELLY', 'token', 'other'),
  ('joe', 'JOE', 'JOE', 'token', 'other'),
  ('jst', 'JST', 'JST', 'token', 'other'),
  ('jto', 'JTO', 'JTO', 'token', 'other'),
  ('jupiter', 'Jupiter', 'JUP', 'protocol', 'defi_aggregator'),
  ('kaia', 'KAIA', 'KAIA', 'token', 'other'),
  ('kaito', 'KAITO', 'KAITO', 'token', 'other'),
  ('kas', 'KAS', 'KAS', 'token', 'other'),
  ('kava', 'KAVA', 'KAVA', 'token', 'other'),
  ('kernel', 'KERNEL', 'KERNEL', 'token', 'other'),
  ('kgen', 'KGEN', 'KGEN', 'token', 'other'),
  ('kite', 'KITE', 'KITE', 'token', 'other'),
  ('kmno', 'KMNO', 'KMNO', 'token', 'other'),
  ('knc', 'KNC', 'KNC', 'token', 'other'),
  ('koma', 'KOMA', 'KOMA', 'token', 'other'),
  ('ksm', 'KSM', 'KSM', 'token', 'other'),
  ('la', 'LA', 'LA', 'token', 'other'),
  ('lab', 'LAB', 'LAB', 'token', 'other'),
  ('layer', 'LAYER', 'LAYER', 'token', 'other'),
  ('lido', 'Lido', 'LDO', 'protocol', 'liquid_staking'),
  ('light', 'LIGHT', 'LIGHT', 'token', 'other'),
  ('linea', 'LINEA', 'LINEA', 'token', 'other'),
  ('lista', 'LISTA', 'LISTA', 'token', 'other'),
  ('lit', 'LIT', 'LIT', 'token', 'other'),
  ('litecoin', 'Litecoin', 'LTC', 'chain', 'l1'),
  ('lpt', 'LPT', 'LPT', 'token', 'other'),
  ('lqty', 'LQTY', 'LQTY', 'token', 'other'),
  ('lrc', 'LRC', 'LRC', 'token', 'other'),
  ('lsk', 'LSK', 'LSK', 'token', 'other'),
  ('lumia', 'LUMIA', 'LUMIA', 'token', 'other'),
  ('luna2', 'LUNA2', 'LUNA2', 'token', 'other'),
  ('lunc', 'LUNC', '1000LUNC', 'token', 'other'),
  ('lyn', 'LYN', 'LYN', 'token', 'other'),
  ('m', 'M', 'M', 'token', 'other'),
  ('magic', 'MAGIC', 'MAGIC', 'token', 'other'),
  ('magma', 'MAGMA', 'MAGMA', 'token', 'other'),
  ('mana', 'MANA', 'MANA', 'token', 'other'),
  ('manta', 'MANTA', 'MANTA', 'token', 'other'),
  ('mask', 'MASK', 'MASK', 'token', 'other'),
  ('mav', 'MAV', 'MAV', 'token', 'other'),
  ('mavia', 'MAVIA', 'MAVIA', 'token', 'other'),
  ('mbox', 'MBOX', 'MBOX', 'token', 'other'),
  ('me', 'ME', 'ME', 'token', 'other'),
  ('melania', 'MELANIA', 'MELANIA', 'token', 'other'),
  ('meme', 'MEME', 'MEME', 'token', 'other'),
  ('merl', 'MERL', 'MERL', 'token', 'other'),
  ('met', 'MET', 'MET', 'token', 'other'),
  ('metis', 'METIS', 'METIS', 'token', 'other'),
  ('mew', 'MEW', 'MEW', 'token', 'other'),
  ('mina', 'MINA', 'MINA', 'token', 'other'),
  ('mira', 'MIRA', 'MIRA', 'token', 'other'),
  ('mito', 'MITO', 'MITO', 'token', 'other'),
  ('mln', 'MLN', 'MLN', 'token', 'other'),
  ('mmt', 'MMT', 'MMT', 'token', 'other'),
  ('mnt', 'MNT', 'MNT', 'token', 'other'),
  ('moca', 'MOCA', 'MOCA', 'token', 'other'),
  ('mon', 'MON', 'MON', 'token', 'other'),
  ('moodeng', 'MOODENG', 'MOODENG', 'token', 'other'),
  ('morpho', 'MORPHO', 'MORPHO', 'token', 'other'),
  ('movr', 'MOVR', 'MOVR', 'token', 'other'),
  ('mtl', 'MTL', 'MTL', 'token', 'other'),
  ('mubarak', 'MUBARAK', 'MUBARAK', 'token', 'other'),
  ('myx', 'MYX', 'MYX', 'token', 'other'),
  ('naoris', 'NAORIS', 'NAORIS', 'token', 'other'),
  ('near', 'NEAR Protocol', 'NEAR', 'chain', 'l1'),
  ('neiro', 'NEIRO', 'NEIRO', 'token', 'other'),
  ('neirocto', 'NEIROCTO', '1000NEIROCTO', 'token', 'other'),
  ('neo', 'NEO', 'NEO', 'token', 'other'),
  ('newt', 'NEWT', 'NEWT', 'token', 'other'),
  ('nfp', 'NFP', 'NFP', 'token', 'other'),
  ('night', 'NIGHT', 'NIGHT', 'token', 'other'),
  ('nil', 'NIL', 'NIL', 'token', 'other'),
  ('nkn', 'NKN', 'NKN', 'token', 'other'),
  ('nmr', 'NMR', 'NMR', 'token', 'other'),
  ('nom', 'NOM', 'NOM', 'token', 'other'),
  ('not', 'NOT', 'NOT', 'token', 'other'),
  ('ntrn', 'NTRN', 'NTRN', 'token', 'other'),
  ('nxpc', 'NXPC', 'NXPC', 'token', 'other'),
  ('og', 'OG', 'OG', 'token', 'other'),
  ('ogn', 'OGN', 'OGN', 'token', 'other'),
  ('okb', 'OKB', 'OKB', 'token', 'other'),
  ('ol', 'OL', 'OL', 'token', 'other'),
  ('om', 'OM', 'OM', 'token', 'other'),
  ('on', 'ON', 'ON', 'token', 'other'),
  ('ondo', 'ONDO', 'ONDO', 'token', 'other'),
  ('one', 'ONE', 'ONE', 'token', 'other'),
  ('ong', 'ONG', 'ONG', 'token', 'other'),
  ('ont', 'ONT', 'ONT', 'token', 'other'),
  ('open', 'OPEN', 'OPEN', 'token', 'other'),
  ('optimism', 'Optimism', 'OP', 'chain', 'l2'),
  ('orca', 'ORCA', 'ORCA', 'token', 'other'),
  ('order', 'ORDER', 'ORDER', 'token', 'other'),
  ('ordi', 'ORDI', 'ORDI', 'token', 'other'),
  ('oxt', 'OXT', 'OXT', 'token', 'other'),
  ('parti', 'PARTI', 'PARTI', 'token', 'other'),
  ('paxg', 'PAXG', 'PAXG', 'token', 'other'),
  ('peaq', 'PEAQ', 'PEAQ', 'token', 'other'),
  ('pendle', 'Pendle', 'PENDLE', 'protocol', 'defi_yield'),
  ('pengu', 'PENGU', 'PENGU', 'token', 'other'),
  ('people', 'PEOPLE', 'PEOPLE', 'token', 'other'),
  ('pepe', 'Pepe', '1000PEPE', 'token', 'meme'),
  ('pha', 'PHA', 'PHA', 'token', 'other'),
  ('phb', 'PHB', 'PHB', 'token', 'other'),
  ('pieverse', 'PIEVERSE', 'PIEVERSE', 'token', 'other'),
  ('pippin', 'PIPPIN', 'PIPPIN', 'token', 'other'),
  ('pixel', 'PIXEL', 'PIXEL', 'token', 'other'),
  ('play', 'PLAY', 'PLAY', 'token', 'other'),
  ('plume', 'PLUME', 'PLUME', 'token', 'other'),
  ('pnut', 'PNUT', 'PNUT', 'token', 'other'),
  ('polkadot', 'Polkadot', 'DOT', 'chain', 'l1'),
  ('polyx', 'POLYX', 'POLYX', 'token', 'other'),
  ('ponke', 'PONKE', 'PONKE', 'token', 'other'),
  ('popcat', 'POPCAT', 'POPCAT', 'token', 'other'),
  ('portal', 'PORTAL', 'PORTAL', 'token', 'other'),
  ('power', 'POWER', 'POWER', 'token', 'other'),
  ('powr', 'POWR', 'POWR', 'token', 'other'),
  ('prom', 'PROM', 'PROM', 'token', 'other'),
  ('prompt', 'PROMPT', 'PROMPT', 'token', 'other'),
  ('prove', 'PROVE', 'PROVE', 'token', 'other'),
  ('ptb', 'PTB', 'PTB', 'token', 'other'),
  ('puffer', 'PUFFER', 'PUFFER', 'token', 'other'),
  ('pumpbtc', 'PUMPBTC', 'PUMPBTC', 'token', 'other'),
  ('pundix', 'PUNDIX', 'PUNDIX', 'token', 'other'),
  ('pyth', 'Pyth Network', 'PYTH', 'protocol', 'oracle'),
  ('q', 'Q', 'Q', 'token', 'other'),
  ('qnt', 'QNT', 'QNT', 'token', 'other'),
  ('qtum', 'QTUM', 'QTUM', 'token', 'other'),
  ('rare', 'RARE', 'RARE', 'token', 'other'),
  ('rats', 'RATS', '1000RATS', 'token', 'other'),
  ('rave', 'RAVE', 'RAVE', 'token', 'other'),
  ('rdnt', 'RDNT', 'RDNT', 'token', 'other'),
  ('recall', 'RECALL', 'RECALL', 'token', 'other'),
  ('red', 'RED', 'RED', 'token', 'other'),
  ('render', 'Render', 'RENDER', 'protocol', 'compute'),
  ('resolv', 'RESOLV', 'RESOLV', 'token', 'other'),
  ('rez', 'REZ', 'REZ', 'token', 'other'),
  ('rif', 'RIF', 'RIF', 'token', 'other'),
  ('ripple', 'XRP', 'XRP', 'chain', 'l1'),
  ('river', 'RIVER', 'RIVER', 'token', 'other'),
  ('rlc', 'RLC', 'RLC', 'token', 'other'),
  ('rls', 'RLS', 'RLS', 'token', 'other'),
  ('roam', 'ROAM', 'ROAM', 'token', 'other'),
  ('ronin', 'RONIN', 'RONIN', 'token', 'other'),
  ('rose', 'ROSE', 'ROSE', 'token', 'other'),
  ('rpl', 'RPL', 'RPL', 'token', 'other'),
  ('rsr', 'RSR', 'RSR', 'token', 'other'),
  ('rune', 'RUNE', 'RUNE', 'token', 'other'),
  ('rvn', 'RVN', 'RVN', 'token', 'other'),
  ('s', 'S', 'S', 'token', 'other'),
  ('safe', 'SAFE', 'SAFE', 'token', 'other'),
  ('saga', 'SAGA', 'SAGA', 'token', 'other'),
  ('sahara', 'SAHARA', 'SAHARA', 'token', 'other'),
  ('sand', 'SAND', 'SAND', 'token', 'other'),
  ('santos', 'SANTOS', 'SANTOS', 'token', 'other'),
  ('sapien', 'SAPIEN', 'SAPIEN', 'token', 'other'),
  ('sats', 'SATS', '1000SATS', 'token', 'other'),
  ('sc', 'SC', 'SC', 'token', 'other'),
  ('scrt', 'SCRT', 'SCRT', 'token', 'other'),
  ('sei', 'Sei', 'SEI', 'chain', 'l1'),
  ('sent', 'SENT', 'SENT', 'token', 'other'),
  ('sfp', 'SFP', 'SFP', 'token', 'other'),
  ('shell', 'SHELL', 'SHELL', 'token', 'other'),
  ('shib', 'SHIB', '1000SHIB', 'token', 'other'),
  ('sign', 'SIGN', 'SIGN', 'token', 'other'),
  ('siren', 'SIREN', 'SIREN', 'token', 'other'),
  ('skl', 'SKL', 'SKL', 'token', 'other'),
  ('sky', 'SKY', 'SKY', 'token', 'other'),
  ('skyai', 'SKYAI', 'SKYAI', 'token', 'other'),
  ('slp', 'SLP', 'SLP', 'token', 'other'),
  ('snt', 'SNT', 'SNT', 'token', 'other'),
  ('solana', 'Solana', 'SOL', 'chain', 'l1'),
  ('solv', 'SOLV', 'SOLV', 'token', 'other'),
  ('somi', 'SOMI', 'SOMI', 'token', 'other'),
  ('sonic', 'SONIC', 'SONIC', 'token', 'other'),
  ('soon', 'SOON', 'SOON', 'token', 'other'),
  ('soph', 'SOPH', 'SOPH', 'token', 'other'),
  ('soso', 'SOSO', 'SOSO', 'token', 'other'),
  ('spell', 'SPELL', 'SPELL', 'token', 'other'),
  ('spk', 'SPK', 'SPK', 'token', 'other'),
  ('sportfun', 'SPORTFUN', 'SPORTFUN', 'token', 'other'),
  ('spx', 'SPX', 'SPX', 'token', 'other'),
  ('sqd', 'SQD', 'SQD', 'token', 'other'),
  ('ssv', 'SSV', 'SSV', 'token', 'other'),
  ('stable', 'STABLE', 'STABLE', 'token', 'other'),
  ('starknet', 'Starknet', 'STRK', 'chain', 'l2'),
  ('stbl', 'STBL', 'STBL', 'token', 'other'),
  ('steem', 'STEEM', 'STEEM', 'token', 'other'),
  ('stg', 'STG', 'STG', 'token', 'other'),
  ('sto', 'STO', 'STO', 'token', 'other'),
  ('storj', 'STORJ', 'STORJ', 'token', 'other'),
  ('stx', 'STX', 'STX', 'token', 'other'),
  ('sui', 'Sui', 'SUI', 'chain', 'l1'),
  ('sun', 'SUN', 'SUN', 'token', 'other'),
  ('super', 'SUPER', 'SUPER', 'token', 'other'),
  ('swarms', 'SWARMS', 'SWARMS', 'token', 'other'),
  ('sxp', 'SXP', 'SXP', 'token', 'other'),
  ('sxt', 'SXT', 'SXT', 'token', 'other'),
  ('syn', 'SYN', 'SYN', 'token', 'other'),
  ('synthetix', 'Synthetix', 'SNX', 'protocol', 'defi_derivatives'),
  ('syrup', 'SYRUP', 'SYRUP', 'token', 'other'),
  ('sys', 'SYS', 'SYS', 'token', 'other'),
  ('t', 'T', 'T', 'token', 'other'),
  ('ta', 'TA', 'TA', 'token', 'other'),
  ('tac', 'TAC', 'TAC', 'token', 'other'),
  ('tag', 'TAG', 'TAG', 'token', 'other'),
  ('taiko', 'TAIKO', 'TAIKO', 'token', 'other'),
  ('take', 'TAKE', 'TAKE', 'token', 'other'),
  ('tanssi', 'TANSSI', 'TANSSI', 'token', 'other'),
  ('the', 'THE', 'THE', 'token', 'other'),
  ('the-graph', 'The Graph', 'GRT', 'protocol', 'indexing'),
  ('theta', 'THETA', 'THETA', 'token', 'other'),
  ('tlm', 'TLM', 'TLM', 'token', 'other'),
  ('tnsr', 'TNSR', 'TNSR', 'token', 'other'),
  ('toncoin', 'Toncoin', 'TON', 'chain', 'l1'),
  ('toshi', 'TOSHI', 'TOSHI', 'token', 'other'),
  ('towns', 'TOWNS', 'TOWNS', 'token', 'other'),
  ('tradoor', 'TRADOOR', 'TRADOOR', 'token', 'other'),
  ('trb', 'TRB', 'TRB', 'token', 'other'),
  ('tree', 'TREE', 'TREE', 'token', 'other'),
  ('tron', 'TRON', 'TRX', 'chain', 'l1'),
  ('trump', 'Trump', 'TRUMP', 'token', 'meme'),
  ('trust', 'TRUST', 'TRUST', 'token', 'other'),
  ('truth', 'TRUTH', 'TRUTH', 'token', 'other'),
  ('tst', 'TST', 'TST', 'token', 'other'),
  ('turbo', 'TURBO', '1000TURBO', 'token', 'other'),
  ('turtle', 'TURTLE', 'TURTLE', 'token', 'other'),
  ('tut', 'TUT', 'TUT', 'token', 'other'),
  ('twt', 'TWT', 'TWT', 'token', 'other'),
  ('uai', 'UAI', 'UAI', 'token', 'other'),
  ('ub', 'UB', 'UB', 'token', 'other'),
  ('uma', 'UMA', 'UMA', 'token', 'other'),
  ('uniswap', 'Uniswap', 'UNI', 'protocol', 'defi_dex'),
  ('us', 'US', 'US', 'token', 'other'),
  ('usd1', 'USD1', 'USD1', 'token', 'other'),
  ('usdc', 'USDC', 'USDC', 'token', 'other'),
  ('usde', 'USDE', 'USDE', 'token', 'other'),
  ('useless', 'USELESS', 'USELESS', 'token', 'other'),
  ('ustc', 'USTC', 'USTC', 'token', 'other'),
  ('usual', 'USUAL', 'USUAL', 'token', 'other'),
  ('vana', 'VANA', 'VANA', 'token', 'other'),
  ('vanry', 'VANRY', 'VANRY', 'token', 'other'),
  ('velo', 'VELO', 'VELO', 'token', 'other'),
  ('velodrome', 'VELODROME', 'VELODROME', 'token', 'other'),
  ('velvet', 'VELVET', 'VELVET', 'token', 'other'),
  ('vet', 'VET', 'VET', 'token', 'other'),
  ('vfy', 'VFY', 'VFY', 'token', 'other'),
  ('vic', 'VIC', 'VIC', 'token', 'other'),
  ('vine', 'VINE', 'VINE', 'token', 'other'),
  ('virtual', 'VIRTUAL', 'VIRTUAL', 'token', 'other'),
  ('vtho', 'VTHO', 'VTHO', 'token', 'other'),
  ('vvv', 'VVV', 'VVV', 'token', 'other'),
  ('w', 'W', 'W', 'token', 'other'),
  ('wal', 'WAL', 'WAL', 'token', 'other'),
  ('waves', 'WAVES', 'WAVES', 'token', 'other'),
  ('waxp', 'WAXP', 'WAXP', 'token', 'other'),
  ('wct', 'WCT', 'WCT', 'token', 'other'),
  ('wld', 'WLD', 'WLD', 'token', 'other'),
  ('xec', 'XEC', '1000XEC', 'token', 'other'),
  ('avantis', 'Avantis', 'AVANTIS', 'protocol', 'defi'),
  ('baby', 'Baby', 'BABY', 'protocol', 'defi'),
  ('backed-finance', 'Backed Finance', 'BACKED-FINANCE', 'protocol', 'defi'),
  ('bal', 'Balancer', 'BAL', 'protocol', 'defi'),
  ('banana', 'Banana', 'BANANA', 'protocol', 'defi'),
  ('bonkbot', 'Bonkbot', 'BONKBOT', 'protocol', 'defi'),
  ('cards', 'Cards', 'CARDS', 'protocol', 'defi'),
  ('comp', 'Compound', 'COMP', 'protocol', 'defi'),
  ('cvx', 'Convex', 'CVX', 'protocol', 'defi'),
  ('dflow', 'DFlow', 'DFLOW', 'protocol', 'defi'),
  ('edgex', 'EdgeX', 'EDGEX', 'protocol', 'defi'),
  ('extended', 'Extended', 'EXTENDED', 'protocol', 'defi'),
  ('falcon-finance', 'Falcon Finance', 'FALCONFINANCE', 'protocol', 'defi'),
  ('felix', 'Felix', 'FELIX', 'protocol', 'defi'),
  ('footballdotfun', 'Football.fun', 'FOOTBALLDOTFUN', 'protocol', 'defi'),
  ('fxs', 'Frax Share', 'FXS', 'protocol', 'defi'),
  ('geod', 'GEODNET', 'GEOD', 'protocol', 'defi'),
  ('gns', 'Gains Network', 'GNS', 'protocol', 'defi'),
  ('hyena', 'Hyena', 'HYENA', 'protocol', 'defi'),
  ('hyperlend', 'HyperLend', 'HYPERLEND', 'protocol', 'defi'),
  ('kalshi', 'Kalshi', 'KALSHI', 'protocol', 'defi'),
  ('kinetiq-markets', 'Kinetiq Markets', 'KINETIQMARKETS', 'protocol', 'defi'),
  ('kntq', 'KNTQ', 'KNTQ', 'protocol', 'defi'),
  ('letsbonk', 'LetsBonk', 'LETSBONK', 'protocol', 'defi'),
  ('lighter', 'Lighter', 'LIGHTER', 'protocol', 'defi'),
  ('limitless', 'Limitless', 'LIMITLESS', 'protocol', 'defi'),
  ('m0', 'M0', 'M0', 'protocol', 'defi'),
  ('mnde', 'Marinade', 'MNDE', 'protocol', 'defi'),
  ('momentum', 'Momentum', 'MOMENTUM', 'protocol', 'defi'),
  ('opinion', 'Opinion', 'OPINION', 'protocol', 'defi'),
  ('ostium', 'Ostium', 'OSTIUM', 'protocol', 'defi'),
  ('paradex', 'Paradex', 'PARADEX', 'protocol', 'defi'),
  ('polymarket', 'Polymarket', 'POLYMARKET', 'protocol', 'defi'),
  ('qi', 'QiDAO', 'QI', 'protocol', 'defi'),
  ('rain', 'Rain', 'RAIN', 'protocol', 'defi'),
  ('superstate', 'Superstate', 'SUPERSTATE', 'protocol', 'defi'),
  ('titan', 'Titan', 'TITAN', 'protocol', 'defi'),
  ('tradexyz', 'Trade.xyz', 'TRADEXYZ', 'protocol', 'defi'),
  ('trufi', 'TrueFi', 'TRUFI', 'protocol', 'defi'),
  ('ventuals', 'Ventuals', 'VENTUALS', 'protocol', 'defi'),
  ('wet', 'WET', 'WET', 'protocol', 'defi'),
  ('xtz', 'Tezos', 'XTZ', 'protocol', 'defi'),
  ('xvs', 'Venus', 'XVS', 'protocol', 'defi'),
  ('zora', 'Zora', 'ZORA', 'protocol', 'defi'),
  ('abstract', 'Abstract', 'ABSTRACT', 'chain', 'l1'),
  ('axs', 'Axie Infinity', 'AXS', 'chain', 'l1'),
  ('base', 'Base', 'BASE', 'chain', 'l1'),
  ('beam', 'Beam', 'BEAM', 'chain', 'l1'),
  ('bgb', 'Bitget', 'BGB', 'chain', 'l1'),
  ('cash', 'Cash', 'CASH', 'chain', 'l1'),
  ('cro', 'Cronos', 'CRO', 'chain', 'l1'),
  ('frqcy', 'FRQCY', 'FRQCY', 'chain', 'l1'),
  ('ftn', 'FTN', 'FTN', 'chain', 'l1'),
  ('hash', 'Hash', 'HASH', 'chain', 'l1'),
  ('hyperevm', 'HyperEVM', 'HYPEREVM', 'chain', 'l1'),
  ('ink', 'Ink', 'INK', 'chain', 'l1'),
  ('kcs', 'KuCoin', 'KCS', 'chain', 'l1'),
  ('leo', 'LEO', 'LEO', 'chain', 'l1'),
  ('luna', 'Terra', 'LUNA', 'chain', 'l1'),
  ('nexo', 'Nexo', 'NEXO', 'chain', 'l1'),
  ('ore', 'ORE', 'ORE', 'chain', 'l1'),
  ('pi', 'Pi Network', 'PI', 'chain', 'l1'),
  ('scroll', 'Scroll', 'SCROLL', 'chain', 'l1'),
  ('tel', 'Telcoin', 'TEL', 'chain', 'l1'),
  ('unichain', 'Unichain', 'UNICHAIN', 'chain', 'l1'),
  ('wlfi', 'World Liberty Financial', 'WLFI', 'chain', 'l1'),
  ('xcn', 'Onyxcoin', 'XCN', 'chain', 'l1'),
  ('xdc', 'XDC', 'XDC', 'chain', 'l1'),
  ('xlayer', 'X Layer', 'XLAYER', 'chain', 'l1'),
  ('xlm', 'Stellar', 'XLM', 'chain', 'l1'),
  ('xmr', 'Monero', 'XMR', 'chain', 'l1'),
  ('zec', 'Zcash', 'ZEC', 'chain', 'l1'),
  ('zk', 'zkSync', 'ZK', 'chain', 'l1'),
  ('binance', 'Binance', 'BINANCE', 'token', 'other'),
  ('bitstamp', 'Bitstamp', 'BITSTAMP', 'token', 'other'),
  ('bybit', 'Bybit', 'BYBIT', 'token', 'other'),
  ('cryptocom', 'Crypto.com', 'CRYPTOCOM', 'token', 'other'),
  ('gate-io', 'Gate.io', 'GATEIO', 'token', 'other'),
  ('gemini', 'Gemini', 'GEMINI', 'token', 'other'),
  ('huobi', 'Huobi', 'HUOBI', 'token', 'other'),
  ('kraken', 'Kraken', 'KRAKEN', 'token', 'other'),
  ('okx', 'OKX', 'OKX', 'token', 'other'),
  ('eq-abtc', 'Equity - ABTC', 'EQ-ABTC', 'token', 'other'),
  ('eq-asst', 'Equity - ASST', 'EQ-ASST', 'token', 'other'),
  ('eq-bmnr', 'Equity - BMNR', 'EQ-BMNR', 'token', 'other'),
  ('eq-bnc', 'Equity - BNC', 'EQ-BNC', 'token', 'other'),
  ('eq-btbt', 'Equity - BTBT', 'EQ-BTBT', 'token', 'other'),
  ('eq-btcs', 'Equity - BTCS', 'EQ-BTCS', 'token', 'other'),
  ('eq-cepo', 'Equity - CEPO', 'EQ-CEPO', 'token', 'other'),
  ('eq-chym', 'Equity - CHYM', 'EQ-CHYM', 'token', 'other'),
  ('eq-coin', 'Equity - Coinbase', 'EQ-COIN', 'token', 'other'),
  ('eq-crcl', 'Equity - Circle', 'EQ-CRCL', 'token', 'other'),
  ('eq-dave', 'Equity - DAVE', 'EQ-DAVE', 'token', 'other'),
  ('eq-dfdv', 'Equity - DFDV', 'EQ-DFDV', 'token', 'other'),
  ('eq-ethm', 'Equity - ETHM', 'EQ-ETHM', 'token', 'other'),
  ('eq-ethz', 'Equity - ETHZ', 'EQ-ETHZ', 'token', 'other'),
  ('eq-etor', 'Equity - ETOR', 'EQ-ETOR', 'token', 'other'),
  ('eq-fgnx', 'Equity - FGNX', 'EQ-FGNX', 'token', 'other'),
  ('eq-figr', 'Equity - FIGR', 'EQ-FIGR', 'token', 'other'),
  ('eq-ford', 'Equity - FORD', 'EQ-FORD', 'token', 'other'),
  ('eq-glxy', 'Equity - Galaxy', 'EQ-GLXY', 'token', 'other'),
  ('eq-hood', 'Equity - Robinhood', 'EQ-HOOD', 'token', 'other'),
  ('eq-hsdt', 'Equity - HSDT', 'EQ-HSDT', 'token', 'other'),
  ('eq-hypd', 'Equity - HYPD', 'EQ-HYPD', 'token', 'other'),
  ('eq-ibkr', 'Equity - IBKR', 'EQ-IBKR', 'token', 'other'),
  ('eq-mstr', 'Equity - MicroStrategy', 'EQ-MSTR', 'token', 'other'),
  ('eq-mtplf', 'Equity - MTPLF', 'EQ-MTPLF', 'token', 'other'),
  ('eq-naka', 'Equity - NAKA', 'EQ-NAKA', 'token', 'other'),
  ('eq-nu', 'Equity - NU', 'EQ-NU', 'token', 'other'),
  ('eq-purr', 'Equity - PURR', 'EQ-PURR', 'token', 'other'),
  ('eq-pypl', 'Equity - PayPal', 'EQ-PYPL', 'token', 'other'),
  ('eq-sata', 'Equity - SATA', 'EQ-SATA', 'token', 'other'),
  ('eq-sbet', 'Equity - SBET', 'EQ-SBET', 'token', 'other'),
  ('eq-schw', 'Equity - Schwab', 'EQ-SCHW', 'token', 'other'),
  ('eq-sofi', 'Equity - SoFi', 'EQ-SOFI', 'token', 'other'),
  ('eq-stss', 'Equity - STSS', 'EQ-STSS', 'token', 'other'),
  ('eq-upxi', 'Equity - UPXI', 'EQ-UPXI', 'token', 'other'),
  ('eq-wt', 'Equity - WisdomTree', 'EQ-WT', 'token', 'other'),
  ('eq-xxi', 'Equity - XXI', 'EQ-XXI', 'token', 'other'),
  ('eq-xyz', 'Equity - XYZ', 'EQ-XYZ', 'token', 'other'),
  ('nasdaq100', 'NASDAQ 100', 'NASDAQ100', 'token', 'other'),
  ('strd', 'Stride', 'STRD', 'token', 'other'),
  ('shiba', 'Shiba Inu', 'SHIBA', 'token', 'other'),
  ('axl', 'Axelar', 'AXL', 'token', 'other'),
  ('cctp', 'CCTP', 'CCTP', 'token', 'other'),
  ('x402', 'X402', 'X402', 'token', 'other'),
  ('buidl', 'BUIDL', 'BUIDL', 'token', 'rwa'),
  ('wtgxx', 'WTGXX', 'WTGXX', 'token', 'rwa'),
  ('xaut', 'Tether Gold', 'XAUT', 'token', 'rwa'),
  ('busd', 'BUSD', 'BUSD', 'token', 'stablecoin'),
  ('crvusd', 'crvUSD', 'CRVUSD', 'token', 'stablecoin'),
  ('cusd', 'CUSD', 'CUSD', 'token', 'stablecoin'),
  ('dai', 'DAI', 'DAI', 'token', 'stablecoin'),
  ('eura', 'EURA', 'EURA', 'token', 'stablecoin'),
  ('eurc', 'EURC', 'EURC', 'token', 'stablecoin'),
  ('eurs', 'EURS', 'EURS', 'token', 'stablecoin'),
  ('fdusd', 'FDUSD', 'FDUSD', 'token', 'stablecoin'),
  ('frxusd', 'frxUSD', 'FRXUSD', 'token', 'stablecoin'),
  ('fxusd', 'fxUSD', 'FXUSD', 'token', 'stablecoin'),
  ('gho', 'GHO', 'GHO', 'token', 'stablecoin'),
  ('gusd', 'GUSD', 'GUSD', 'token', 'stablecoin'),
  ('jupusd', 'JupUSD', 'JUPUSD', 'token', 'stablecoin'),
  ('lisusd', 'lisUSD', 'LISUSD', 'token', 'stablecoin'),
  ('lusd', 'LUSD', 'LUSD', 'token', 'stablecoin'),
  ('mim', 'MIM', 'MIM', 'token', 'stablecoin'),
  ('pyusd', 'PayPal USD', 'PYUSD', 'token', 'stablecoin'),
  ('rlusd', 'RLUSD', 'RLUSD', 'token', 'stablecoin'),
  ('s-usd', 'sUSD', 'SUSD', 'token', 'stablecoin'),
  ('tusd', 'TrueUSD', 'TUSD', 'token', 'stablecoin'),
  ('usd*', 'USD*', 'USD*', 'token', 'stablecoin'),
  ('usd0', 'USD0', 'USD0', 'token', 'stablecoin'),
  ('usda', 'USDA', 'USDA', 'token', 'stablecoin'),
  ('usdd', 'USDD', 'USDD', 'token', 'stablecoin'),
  ('usdf', 'USDF', 'USDF', 'token', 'stablecoin'),
  ('usdfalcon', 'USD Falcon', 'USDFALCON', 'token', 'stablecoin'),
  ('usdg', 'USDG', 'USDG', 'token', 'stablecoin'),
  ('usdp', 'USDP', 'USDP', 'token', 'stablecoin'),
  ('usds', 'USDS', 'USDS', 'token', 'stablecoin'),
  ('usdt', 'USDT', 'USDT', 'token', 'stablecoin'),
  ('usdt0', 'USDT0', 'USDT0', 'token', 'stablecoin'),
  ('usdtb', 'USDtb', 'USDTB', 'token', 'stablecoin'),
  ('usdy', 'USDY', 'USDY', 'token', 'stablecoin'),
  ('usdz', 'USDZ', 'USDZ', 'token', 'stablecoin'),
  ('usn', 'USN', 'USN', 'token', 'stablecoin'),
  ('usr', 'USR', 'USR', 'token', 'stablecoin'),
  ('aca', 'Acala', 'ACA', 'token', 'other'),
  ('aeur', 'AEUR', 'AEUR', 'token', 'other'),
  ('aftermath', 'Aftermath', 'AFTERMATH', 'token', 'other'),
  ('alot', 'Dexalot', 'ALOT', 'token', 'other'),
  ('angle-usd', 'Angle USD', 'ANGLEUSD', 'token', 'other'),
  ('bedrock', 'Bedrock', 'BEDROCK', 'token', 'other'),
  ('benji', 'Benji', 'BENJI', 'token', 'other'),
  ('black', 'Black', 'BLACK', 'token', 'other'),
  ('blue', 'Blue', 'BLUE', 'token', 'other'),
  ('bnc', 'Bifrost', 'BNC', 'token', 'other'),
  ('bold', 'Bold', 'BOLD', 'token', 'other'),
  ('brla', 'BRLA', 'BRLA', 'token', 'other'),
  ('ceur', 'CEUR', 'CEUR', 'token', 'other'),
  ('cfg', 'Centrifuge', 'CFG', 'token', 'other'),
  ('cgusd', 'CGUSD', 'CGUSD', 'token', 'other'),
  ('ckes', 'CKES', 'CKES', 'token', 'other'),
  ('creal', 'CREAL', 'CREAL', 'token', 'other'),
  ('deusd', 'DEUSD', 'DEUSD', 'token', 'other'),
  ('dimo', 'DIMO', 'DIMO', 'token', 'other'),
  ('dodo', 'DODO', 'DODO', 'token', 'other'),
  ('dola', 'DOLA', 'DOLA', 'token', 'other'),
  ('egp', 'EGP', 'EGP', 'token', 'other'),
  ('eos', 'EOS', 'EOS', 'token', 'other'),
  ('eurt', 'EURT', 'EURT', 'token', 'other'),
  ('flexusd', 'FlexUSD', 'FLEXUSD', 'token', 'other'),
  ('fuse', 'Fuse', 'FUSE', 'token', 'other'),
  ('gfi', 'Goldfinch', 'GFI', 'token', 'other'),
  ('glmr', 'Moonbeam', 'GLMR', 'token', 'other'),
  ('hdx', 'HydraDX', 'HDX', 'token', 'other'),
  ('hold', 'Hold', 'HOLD', 'token', 'other'),
  ('honey', 'Honey', 'HONEY', 'token', 'other'),
  ('idrt', 'IDRT', 'IDRT', 'token', 'other'),
  ('idrx', 'IDRX', 'IDRX', 'token', 'other'),
  ('intain', 'Intain', 'INTAIN', 'token', 'other'),
  ('janus', 'Janus', 'JANUS', 'token', 'other'),
  ('jewel', 'DeFi Kingdoms', 'JEWEL', 'token', 'other'),
  ('kar', 'Karura', 'KAR', 'token', 'other'),
  ('kep', 'KEP', 'KEP', 'token', 'other'),
  ('launchcoin', 'LaunchCoin', 'LAUNCHCOIN', 'token', 'other'),
  ('ll', 'LL', 'LL', 'token', 'other'),
  ('lvlusd', 'lvlUSD', 'LVLUSD', 'token', 'other'),
  ('mcb', 'MCDEX', 'MCB', 'token', 'other'),
  ('mento', 'Mento', 'MENTO', 'token', 'other'),
  ('mercado-bitcoin', 'Mercado Bitcoin', 'MERCADOBITCOIN', 'token', 'other'),
  ('myriadmarket', 'Myriad Market', 'MYRIADMARKET', 'token', 'other'),
  ('myth', 'Mythos', 'MYTH', 'token', 'other'),
  ('neon', 'Neon', 'NEON', 'token', 'other'),
  ('neuro', 'Neuro', 'NEURO', 'token', 'other'),
  ('pact', 'Pact', 'PACT', 'token', 'other'),
  ('rainbow-bridge', 'Rainbow Bridge', 'RAINBOWBRIDGE', 'token', 'other'),
  ('ref', 'Ref Finance', 'REF', 'token', 'other'),
  ('saros', 'Saros', 'SAROS', 'token', 'other'),
  ('soneium', 'Soneium', 'SONEIUM', 'token', 'other'),
  ('sonne', 'Sonne', 'SONNE', 'token', 'other'),
  ('susd', 'sUSD', 'SUSD', 'token', 'other'),
  ('tradable', 'Tradable', 'TRADABLE', 'token', 'other'),
  ('tryb', 'TRYB', 'TRYB', 'token', 'other'),
  ('usd3', 'USD3', 'USD3', 'token', 'other'),
  ('usdglo', 'USDGLO', 'USDGLO', 'token', 'other'),
  ('usdx', 'USDX', 'USDX', 'token', 'other'),
  ('usdxl', 'USDXL', 'USDXL', 'token', 'other'),
  ('xfi', 'CrossFi', 'XFI', 'token', 'other'),
  ('zkcro', 'zkCRO', 'ZKCRO', 'token', 'other'),
  ('zrc', 'ZRC', 'ZRC', 'token', 'other'),
  ('icpswap', 'ICPSwap', 'ICPSWAP', 'protocol', 'defi_dex'),
  ('xexchange', 'xExchange', 'XEXCHANGE', 'protocol', 'defi_dex'),
  ('t-rize', 'T RIZE', 'TRIZE', 'token', 'rwa'),
  ('bwatch', 'Bwatch', 'BWATCH', 'protocol', 'defi_dex'),
  ('flexa', 'Flexa', 'FLEXA', 'token', 'other'),
  ('bifi', 'BiFi', 'BIFI', 'protocol', 'defi_lending'),
  ('zyfai', 'ZyFAI', 'ZYFAI', 'token', 'other'),
  ('railgun', 'Railgun', 'RAILGUN', 'token', 'other'),
  ('acryptos', 'ACryptoS', 'ACRYPTOS', 'token', 'other'),
  ('indigo', 'Indigo', 'INDIGO', 'token', 'other'),
  ('kinetic', 'Kinetic', 'KINETIC', 'protocol', 'defi_lending'),
  ('sushiswap', 'SushiSwap', 'SUSHISWAP', 'protocol', 'defi_dex'),
  ('superfluid', 'Superfluid', 'SUPERFLUID', 'token', 'other'),
  ('zircuit', 'Zircuit', 'ZIRCUIT', 'chain', 'l1'),
  ('lumenswap', 'LumenSwap', 'LUMENSWAP', 'protocol', 'defi_dex'),
  ('chainflip', 'Chainflip', 'CHAINFLIP', 'chain', 'l1'),
  ('swissborg', 'SwissBorg', 'SWISSBORG', 'token', 'other'),
  ('gearbox', 'Gearbox', 'GEARBOX', 'protocol', 'defi_lending'),
  ('mansory', 'Mansory', 'MANSORY', 'token', 'rwa'),
  ('pnetwork', 'pNetwork', 'PNETWORK', 'protocol', 'bridge'),
  ('hegic', 'Hegic', 'HEGIC', 'token', 'other'),
  ('tectonic', 'Tectonic', 'TECTONIC', 'protocol', 'defi_lending'),
  ('storm-trade', 'Storm Trade', 'STORMTRADE', 'protocol', 'defi_derivatives'),
  ('stacks', 'Stacks', 'STACKS', 'chain', 'l1'),
  ('hyperliquid-l1', 'Hyperliquid L1', 'HYPERLIQUI', 'chain', 'l1'),
  ('enzyme-finance', 'Enzyme Finance', 'ENZYMEFINA', 'protocol', 'defi_dex'),
  ('gnosis', 'Gnosis', 'GNOSIS', 'chain', 'l1'),
  ('eigencloud', 'EigenCloud', 'EIGENCLOUD', 'token', 'other'),
  ('angle', 'Angle', 'ANGLE', 'token', 'other'),
  ('flashtrade', 'FlashTrade', 'FLASHTRADE', 'protocol', 'defi_derivatives'),
  ('maya-protocol', 'Maya Protocol', 'MAYAPROTOC', 'chain', 'l1'),
  ('aura', 'Aura', 'AURA', 'token', 'other'),
  ('nexus-mutual', 'Nexus Mutual', 'NEXUSMUTUA', 'token', 'other'),
  ('doge', 'Doge', 'DOGE', 'chain', 'l1'),
  ('astroport', 'Astroport', 'ASTROPORT', 'protocol', 'defi_dex'),
  ('stride', 'Stride', 'STRIDE', 'chain', 'l1'),
  ('blazestake', 'BlazeStake', 'BLAZESTAKE', 'token', 'other'),
  ('kava-lend', 'Kava Lend', 'KAVALEND', 'protocol', 'defi_lending'),
  ('bitmex', 'Bitmex', 'BITMEX', 'token', 'other'),
  ('rootstock', 'Rootstock', 'ROOTSTOCK', 'chain', 'l1'),
  ('icp', 'ICP', 'ICP', 'chain', 'l1'),
  ('belt-finance', 'Belt Finance', 'BELTFINANC', 'token', 'other'),
  ('chainge-finance', 'Chainge Finance', 'CHAINGEFIN', 'protocol', 'defi_dex'),
  ('berachain', 'Berachain', 'BERACHAIN', 'chain', 'l1'),
  ('reserve-protocol', 'Reserve Protocol', 'RESERVEPRO', 'protocol', 'defi_dex'),
  ('binance-cex', 'Binance CEX', 'BINANCECEX', 'chain', 'l1'),
  ('fraxtal', 'Fraxtal', 'FRAXTAL', 'chain', 'l1'),
  ('bitkub', 'Bitkub', 'BITKUB', 'chain', 'l1'),
  ('paxos-gold', 'Paxos Gold', 'PAXOSGOLD', 'token', 'rwa'),
  ('bonzo-finance', 'Bonzo Finance', 'BONZOFINAN', 'protocol', 'defi_lending'),
  ('loopring', 'Loopring', 'LOOPRING', 'protocol', 'defi_dex'),
  ('stables-labs-usdx', 'Stables Labs USDX', 'STABLESLAB', 'token', 'other'),
  ('bifrost-network', 'Bifrost Network', 'BIFROSTNET', 'chain', 'l1'),
  ('flokifi-locker', 'FlokiFi Locker', 'FLOKIFILOC', 'token', 'other'),
  ('serum', 'Serum', 'SERUM', 'protocol', 'defi_dex'),
  ('stellar', 'Stellar', 'STELLAR', 'chain', 'l1'),
  ('multiversx', 'MultiversX', 'MULTIVERSX', 'chain', 'l1'),
  ('rocket-pool', 'Rocket Pool', 'ROCKETPOOL', 'token', 'other'),
  ('aave-v2', 'Aave V2', 'AAVEV2', 'protocol', 'defi_lending'),
  ('obol', 'Obol', 'OBOL', 'token', 'other'),
  ('plume-mainnet', 'Plume Mainnet', 'PLUMEMAINN', 'chain', 'l1'),
  ('blackrock-buidl', 'BlackRock BUIDL', 'BLACKROCKB', 'token', 'rwa'),
  ('harvest-finance', 'Harvest Finance', 'HARVESTFIN', 'token', 'other'),
  ('immutable-zkevm', 'Immutable zkEVM', 'IMMUTABLEZ', 'chain', 'l1'),
  ('x-layer', 'X Layer', 'XLAYER', 'chain', 'l1'),
  ('flare', 'Flare', 'FLARE', 'chain', 'l1'),
  ('zeus-network', 'Zeus Network', 'ZEUSNETWOR', 'token', 'other'),
  ('overnight-finance', 'Overnight Finance', 'OVERNIGHTF', 'token', 'other'),
  ('xsy', 'XSY', 'XSY', 'token', 'other'),
  ('movement', 'Movement', 'MOVEMENT', 'chain', 'l1'),
  ('stake-dao', 'Stake DAO', 'STAKEDAO', 'token', 'other'),
  ('gravity-bridge', 'Gravity Bridge', 'GRAVITYBRI', 'protocol', 'bridge'),
  ('coinex', 'CoinEx', 'COINEX', 'chain', 'l1'),
  ('synapse', 'Synapse', 'SYNAPSE', 'chain', 'l1'),
  ('orbit-bridge', 'Orbit Bridge', 'ORBITBRIDG', 'protocol', 'bridge'),
  ('polygon', 'Polygon', 'POLYGON', 'chain', 'l1'),
  ('ichi', 'ICHI', 'ICHI', 'token', 'other'),
  ('merlinswap', 'MerlinSwap', 'MERLINSWAP', 'protocol', 'defi_dex'),
  ('looped-hype', 'Looped Hype', 'LOOPEDHYPE', 'token', 'other'),
  ('yield-yak-aggregator', 'Yield Yak Aggregator', 'YIELDYAKAG', 'token', 'other'),
  ('osmosis', 'Osmosis', 'OSMOSIS', 'chain', 'l1'),
  ('benqi-lending', 'Benqi Lending', 'BENQILENDI', 'protocol', 'defi_lending'),
  ('octus-bridge', 'Octus Bridge', 'OCTUSBRIDG', 'protocol', 'bridge'),
  ('republic-note', 'Republic Note', 'REPUBLICNO', 'token', 'rwa'),
  ('beefy', 'Beefy', 'BEEFY', 'token', 'other'),
  ('myx-finance', 'MYX Finance', 'MYXFINANCE', 'protocol', 'defi_derivatives'),
  ('yield-basis', 'Yield Basis', 'YIELDBASIS', 'token', 'other'),
  ('pinksale', 'PinkSale', 'PINKSALE', 'token', 'other'),
  ('gravity-by-galxe', 'Gravity by Galxe', 'GRAVITYBYG', 'chain', 'l1'),
  ('proxy', 'Proxy', 'PROXY', 'protocol', 'bridge'),
  ('dolomite', 'Dolomite', 'DOLOMITE', 'protocol', 'defi_lending'),
  ('astar', 'Astar', 'ASTAR', 'chain', 'l1'),
  ('gains-network', 'Gains Network', 'GAINSNETWO', 'protocol', 'defi_derivatives'),
  ('youves', 'Youves', 'YOUVES', 'token', 'other'),
  ('geth', 'GETH', 'GETH', 'token', 'other'),
  ('morpheusai', 'MorpheusAI', 'MORPHEUSAI', 'token', 'other'),
  ('monad', 'Monad', 'MONAD', 'chain', 'l1'),
  ('treehouse-protocol', 'Treehouse Protocol', 'TREEHOUSEP', 'token', 'other'),
  ('index-coop', 'Index Coop', 'INDEXCOOP', 'protocol', 'defi_dex'),
  ('badger-dao', 'Badger DAO', 'BADGERDAO', 'token', 'other'),
  ('blur-bids', 'Blur Bids', 'BLURBIDS', 'token', 'other'),
  ('verus', 'Verus', 'VERUS', 'chain', 'l1'),
  ('taiko-bridge', 'Taiko Bridge', 'TAIKOBRIDG', 'protocol', 'bridge'),
  ('paycash', 'PayCash', 'PAYCASH', 'protocol', 'defi_dex'),
  ('bitkan', 'BitKan', 'BITKAN', 'token', 'other'),
  ('mantle', 'Mantle', 'MANTLE', 'chain', 'l1'),
  ('plasma', 'Plasma', 'PLASMA', 'chain', 'l1'),
  ('connext', 'Connext', 'CONNEXT', 'protocol', 'bridge'),
  ('tezos', 'Tezos', 'TEZOS', 'chain', 'l1'),
  ('hypha', 'Hypha', 'HYPHA', 'token', 'other'),
  ('zksync-era', 'zkSync Era', 'ZKSYNCERA', 'chain', 'l1'),
  ('unirouter', 'UniRouter', 'UNIROUTER', 'protocol', 'bridge'),
  ('xdai-stake-bridge', 'xDAI Stake Bridge', 'XDAISTAKEB', 'protocol', 'bridge'),
  ('vaulta', 'Vaulta', 'VAULTA', 'chain', 'l1'),
  ('weex', 'WEEX', 'WEEX', 'token', 'other'),
  ('yieldnest', 'YieldNest', 'YIELDNEST', 'chain', 'l1'),
  ('ston.fi', 'STON.fi', 'STON.FI', 'protocol', 'defi_dex'),
  ('debridge', 'deBridge', 'DEBRIDGE', 'protocol', 'bridge'),
  ('justlend', 'JustLend', 'JUSTLEND', 'protocol', 'defi_lending'),
  ('dxsale', 'DxSale', 'DXSALE', 'token', 'other'),
  ('brickken', 'Brickken', 'BRICKKEN', 'token', 'rwa'),
  ('realms', 'Realms', 'REALMS', 'token', 'other'),
  ('liqwid', 'Liqwid', 'LIQWID', 'protocol', 'defi_lending'),
  ('metalx-lending', 'MetalX Lending', 'METALXLEND', 'protocol', 'defi_lending'),
  ('quickswap-dex', 'Quickswap Dex', 'QUICKSWAPD', 'protocol', 'defi_dex'),
  ('alchemix', 'Alchemix', 'ALCHEMIX', 'token', 'other'),
  ('aquarius-stellar', 'Aquarius Stellar', 'AQUARIUSST', 'protocol', 'defi_dex'),
  ('beraborrow', 'Beraborrow', 'BERABORROW', 'token', 'other'),
  ('world-chain', 'World Chain', 'WORLDCHAIN', 'chain', 'l1'),
  ('amnis-finance', 'Amnis Finance', 'AMNISFINAN', 'token', 'other'),
  ('idle', 'Idle', 'IDLE', 'token', 'other'),
  ('phemex', 'Phemex', 'PHEMEX', 'token', 'other'),
  ('vesper', 'Vesper', 'VESPER', 'token', 'other'),
  ('across', 'Across', 'ACROSS', 'chain', 'l1'),
  ('linear-protocol', 'LiNEAR Protocol', 'LINEARPROT', 'token', 'other'),
  ('minswap', 'Minswap', 'MINSWAP', 'protocol', 'defi_dex'),
  ('merkle-trade', 'Merkle Trade', 'MERKLETRAD', 'protocol', 'defi_derivatives'),
  ('cbridge', 'cBridge', 'CBRIDGE', 'protocol', 'bridge'),
  ('hop-protocol', 'Hop Protocol', 'HOPPROTOCO', 'chain', 'l1'),
  ('origyn', 'ORIGYN', 'ORIGYN', 'token', 'rwa'),
  ('nibiru', 'Nibiru', 'NIBIRU', 'chain', 'l1'),
  ('symmio', 'SYMMIO', 'SYMMIO', 'protocol', 'defi_derivatives'),
  ('blueshift', 'Blueshift', 'BLUESHIFT', 'protocol', 'defi_dex'),
  ('boson-protocol', 'Boson Protocol', 'BOSONPROTO', 'token', 'rwa'),
  ('wombat-exchange', 'Wombat Exchange', 'WOMBATEXCH', 'protocol', 'defi_dex'),
  ('qidao', 'QiDao', 'QIDAO', 'token', 'other'),
  ('stader', 'Stader', 'STADER', 'token', 'other'),
  ('concentrator', 'Concentrator', 'CONCENTRAT', 'token', 'other'),
  ('resupply', 'Resupply', 'RESUPPLY', 'protocol', 'defi_lending'),
  ('apechain', 'ApeChain', 'APECHAIN', 'chain', 'l1'),
  ('anvil', 'Anvil', 'ANVIL', 'token', 'other'),
  ('frankencoin', 'Frankencoin', 'FRANKENCOI', 'token', 'other'),
  ('fantom', 'Fantom', 'FANTOM', 'chain', 'l1'),
  ('zerobase-cedefi', 'ZEROBASE CeDeFi', 'ZEROBASECE', 'token', 'other'),
  ('satlayer', 'SatLayer', 'SATLAYER', 'token', 'other'),
  ('ekubo', 'Ekubo', 'EKUBO', 'protocol', 'defi_dex'),
  ('ontology', 'Ontology', 'ONTOLOGY', 'chain', 'l1'),
  ('babylon-genesis', 'Babylon Genesis', 'BABYLONGEN', 'chain', 'l1'),
  ('veno-finance', 'Veno Finance', 'VENOFINANC', 'token', 'other'),
  ('powercity-earn-protocol', 'POWERCITY Earn Protocol', 'POWERCITYE', 'token', 'other'),
  ('xpr-network', 'XPR Network', 'XPRNETWORK', 'chain', 'l1'),
  ('wingriders', 'WingRiders', 'WINGRIDERS', 'protocol', 'defi_dex'),
  ('piku', 'Piku', 'PIKU', 'token', 'other'),
  ('aelf', 'aelf', 'AELF', 'chain', 'l1'),
  ('penpie', 'Penpie', 'PENPIE', 'token', 'other'),
  ('iotex', 'IoTeX', 'IOTEX', 'chain', 'l1'),
  ('harmonix-finance', 'Harmonix Finance', 'HARMONIXFI', 'token', 'other'),
  ('stusdt', 'stUSDT', 'STUSDT', 'token', 'rwa'),
  ('fx-protocol', 'fx Protocol', 'FXPROTOCOL', 'token', 'stablecoin'),
  ('sphere-finance', 'Sphere Finance', 'SPHEREFINA', 'token', 'other'),
  ('dedust', 'DeDust', 'DEDUST', 'protocol', 'defi_dex'),
  ('xwin-finance', 'xWin Finance', 'XWINFINANC', 'protocol', 'defi_dex'),
  ('equilibria', 'Equilibria', 'EQUILIBRIA', 'token', 'other'),
  ('wing-finance', 'Wing Finance', 'WINGFINANC', 'protocol', 'defi_lending'),
  ('keep3r-network', 'Keep3r Network', 'KEEP3RNETW', 'protocol', 'defi_derivatives'),
  ('hedera', 'Hedera', 'HEDERA', 'chain', 'l1'),
  ('sophon', 'Sophon', 'SOPHON', 'chain', 'l1'),
  ('renzo', 'Renzo', 'RENZO', 'token', 'other'),
  ('terra2', 'Terra2', 'TERRA2', 'chain', 'l1'),
  ('moneyonchain', 'MoneyOnChain', 'MONEYONCHA', 'token', 'stablecoin'),
  ('lisk', 'Lisk', 'LISK', 'chain', 'l1'),
  ('icon', 'Icon', 'ICON', 'chain', 'l1'),
  ('ethereal', 'Ethereal', 'ETHEREAL', 'chain', 'l1'),
  ('ronin-bridge', 'Ronin Bridge', 'RONINBRIDG', 'protocol', 'bridge'),
  ('equilibre', 'Equilibre', 'EQUILIBRE', 'protocol', 'defi_dex'),
  ('pulsechain', 'Pulsechain', 'PULSECHAIN', 'chain', 'l1'),
  ('gamma', 'Gamma', 'GAMMA', 'token', 'other'),
  ('xrpl', 'XRPL', 'XRPL', 'chain', 'l1'),
  ('layerbank', 'LayerBank', 'LAYERBANK', 'protocol', 'defi_lending'),
  ('inverse-finance-firm', 'Inverse Finance FiRM', 'INVERSEFIN', 'token', 'other'),
  ('unitus', 'Unitus', 'UNITUS', 'protocol', 'defi_lending'),
  ('hakka-finance', 'Hakka Finance', 'HAKKAFINAN', 'protocol', 'defi_derivatives'),
  ('uranium.io', 'Uranium.io', 'URANIUM.IO', 'token', 'rwa'),
  ('wemix3.0', 'WEMIX3.0', 'WEMIX3.0', 'chain', 'l1'),
  ('abc-pool', 'ABC Pool', 'ABCPOOL', 'token', 'other'),
  ('deltaprime', 'DeltaPrime', 'DELTAPRIME', 'token', 'other'),
  ('iron-bank', 'Iron Bank', 'IRONBANK', 'protocol', 'defi_lending'),
  ('zigchain', 'ZIGChain', 'ZIGCHAIN', 'chain', 'l1'),
  ('saber', 'Saber', 'SABER', 'protocol', 'defi_dex'),
  ('chiliz', 'Chiliz', 'CHILIZ', 'chain', 'l1'),
  ('turbos', 'Turbos', 'TURBOS', 'protocol', 'defi_dex'),
  ('clever', 'CLever', 'CLEVER', 'token', 'other'),
  ('peapods-finance', 'Peapods Finance', 'PEAPODSFIN', 'token', 'other'),
  ('tornado-cash', 'Tornado Cash', 'TORNADOCAS', 'token', 'other'),
  ('autofarm', 'Autofarm', 'AUTOFARM', 'token', 'other'),
  ('thalaswap', 'ThalaSwap', 'THALASWAP', 'protocol', 'defi_dex'),
  ('tinyman', 'Tinyman', 'TINYMAN', 'protocol', 'defi_dex'),
  ('radpie', 'Radpie', 'RADPIE', 'token', 'other'),
  ('team-finance', 'Team Finance', 'TEAMFINANC', 'token', 'other'),
  ('conflux', 'Conflux', 'CONFLUX', 'chain', 'l1'),
  ('hawkfi', 'HawkFi', 'HAWKFI', 'token', 'other'),
  ('bio-protocol', 'Bio Protocol', 'BIOPROTOCO', 'token', 'other'),
  ('zerolend-lending', 'ZeroLend Lending', 'ZEROLENDLE', 'protocol', 'defi_lending'),
  ('probit-global', 'ProBit Global', 'PROBITGLOB', 'token', 'other'),
  ('vires-finance', 'Vires Finance', 'VIRESFINAN', 'protocol', 'defi_lending'),
  ('map-protocol', 'MAP Protocol', 'MAPPROTOCO', 'chain', 'l1'),
  ('stafi', 'Stafi', 'STAFI', 'chain', 'l1'),
  ('tranchess-yield', 'Tranchess Yield', 'TRANCHESSY', 'token', 'other'),
  ('splash-protocol', 'Splash Protocol', 'SPLASHPROT', 'protocol', 'defi_dex'),
  ('cvault-finance', 'cVault Finance', 'CVAULTFINA', 'token', 'other'),
  ('ferro', 'Ferro', 'FERRO', 'protocol', 'defi_dex'),
  ('bifrost', 'Bifrost', 'BIFROST', 'chain', 'l1'),
  ('pickle', 'Pickle', 'PICKLE', 'token', 'other'),
  ('mixin', 'Mixin', 'MIXIN', 'chain', 'l1'),
  ('sdai', 'sDAI', 'SDAI', 'token', 'other'),
  ('autofinance', 'AUTOfinance', 'AUTOFINANC', 'token', 'other'),
  ('the-idols', 'The Idols', 'THEIDOLS', 'token', 'other'),
  ('hydration', 'Hydration', 'HYDRATION', 'chain', 'l1'),
  ('meth-protocol', 'mETH Protocol', 'METHPROTOC', 'token', 'other'),
  ('hamilton-lane-senior-credit-opportunities-securitize-fund', 'Hamilton Lane Senior Credit Opportunities Securitize Fund', 'HAMILTONLA', 'token', 'rwa'),
  ('provenance', 'Provenance', 'PROVENANCE', 'chain', 'l1'),
  ('gyroscope-gyd', 'Gyroscope GYD', 'GYROSCOPEG', 'token', 'stablecoin'),
  ('easedefi.org', 'Easedefi.org', 'EASEDEFI.O', 'token', 'other'),
  ('multichain', 'Multichain', 'MULTICHAIN', 'protocol', 'bridge'),
  ('kpk', 'kpk', 'KPK', 'token', 'other'),
  ('aktionariat', 'Aktionariat', 'AKTIONARIA', 'token', 'rwa'),
  ('symbiosis', 'Symbiosis', 'SYMBIOSIS', 'chain', 'l1'),
  ('mode', 'Mode', 'MODE', 'chain', 'l1'),
  ('thorchain', 'Thorchain', 'THORCHAIN', 'chain', 'l1'),
  ('waterneuron', 'WaterNeuron', 'WATERNEURO', 'token', 'other'),
  ('liquidloans', 'LiquidLoans', 'LIQUIDLOAN', 'token', 'other'),
  ('convex-finance', 'Convex Finance', 'CONVEXFINA', 'token', 'other'),
  ('alphalend', 'AlphaLend', 'ALPHALEND', 'protocol', 'defi_lending'),
  ('0x-aggregator', '0x Aggregator', '0XAGGREGAT', 'protocol', 'defi_dex'),
  ('agora-dollar', 'Agora Dollar', 'AGORADOLLA', 'token', 'stablecoin'),
  ('altlayer', 'AltLayer', 'ALTLAYER', 'token', 'other'),
  ('arkham', 'Arkham', 'ARKHAM', 'token', 'other'),
  ('axie-infinity', 'Axie Infinity', 'AXIEINFINI', 'token', 'other'),
  ('banana-gun', 'Banana Gun', 'BANANAGUN', 'token', 'other'),
  ('basedmarkets', 'basedmarkets', 'BASEDMARKE', 'protocol', 'defi_derivatives'),
  ('celo-dollar', 'Celo Dollar', 'CELODOLLAR', 'token', 'stablecoin'),
  ('celo-euro', 'Celo Euro', 'CELOEURO', 'token', 'stablecoin'),
  ('celo-real', 'Celo Real', 'CELOREAL', 'token', 'stablecoin'),
  ('chronicle', 'Chronicle', 'CHRONICLE', 'token', 'other'),
  ('falcon-usd', 'Falcon USD', 'FALCONUSD', 'token', 'stablecoin'),
  ('helium-network', 'Helium Network', 'HELIUMNETW', 'token', 'other'),
  ('houdini-swap', 'Houdini Swap', 'HOUDINISWA', 'protocol', 'defi_dex'),
  ('layerzero', 'LayerZero', 'LAYERZERO', 'protocol', 'bridge'),
  ('magic-internet-money', 'Magic Internet Money', 'MAGICINTER', 'token', 'stablecoin'),
  ('metadao', 'MetaDAO', 'METADAO', 'protocol', 'defi_dex'),
  ('metaplex', 'Metaplex', 'METAPLEX', 'token', 'other'),
  ('mstable-usd', 'mStable USD', 'MSTABLEUSD', 'token', 'stablecoin'),
  ('official-trump', 'Official Trump', 'OFFICIALTR', 'token', 'other'),
  ('olympus-dao', 'Olympus DAO', 'OLYMPUSDAO', 'token', 'other'),
  ('ondo-us-dollar-yield', 'Ondo US Dollar Yield', 'ONDOUSDOLL', 'token', 'stablecoin'),
  ('op-mainnet', 'OP Mainnet', 'OPMAINNET', 'chain', 'l1'),
  ('pudgy-penguins', 'Pudgy Penguins', 'PUDGYPENGU', 'token', 'other'),
  ('pump.fun', 'pump.fun', 'PUMP.FUN', 'token', 'other'),
  ('request-network', 'Request Network', 'REQUESTNET', 'token', 'other'),
  ('resolv-usd', 'Resolv USD', 'RESOLVUSD', 'token', 'stablecoin'),
  ('sky-dollar', 'Sky Dollar', 'SKYDOLLAR', 'token', 'stablecoin'),
  ('thorswap', 'THORSwap', 'THORSWAP', 'protocol', 'defi_dex'),
  ('tornado-finance', 'Tornado Finance', 'TORNADOFIN', 'token', 'other'),
  ('walrus-protocol', 'Walrus Protocol', 'WALRUSPROT', 'token', 'other'),
  ('aerodrome-finance', 'Aerodrome', 'AERO', 'protocol', ''),
  ('aftermath-token', 'Aftermath Finance', 'AFT', 'protocol', ''),
  ('aevo-exchange', 'Aevo', 'AEVO', 'protocol', ''),
  ('axelar', 'Axelar', 'AXL', 'protocol', ''),
  ('ether-fi', 'ether.fi', 'ETHFI', 'protocol', ''),
  ('euler', 'Euler', 'EUL', 'protocol', ''),
  ('jito-governance-token', 'Jito', 'JTO', 'protocol', ''),
  ('kamino', 'Kamino', 'KMNO', 'protocol', ''),
  ('liquity', 'Liquity', 'LQTY', 'protocol', ''),
  ('stargate-finance', 'Stargate Finance', 'STG', 'protocol', ''),
  ('syrup-finance', 'Maple Finance', 'SYRUP', 'protocol', ''),
  ('cronos', 'Cronos', 'CRO', 'chain', ''),
  ('infrared', 'Infrared Finance', 'IR', 'protocol', ''),
  ('pax-gold', 'Paxos Gold', 'PAXG', 'token', '')
ON CONFLICT (canonical_id) DO NOTHING;

INSERT INTO entity_source_ids (entity_id, source, source_id)
SELECT e.entity_id, v.source, v.source_id FROM (VALUES
  ('000babydoge', 'velo', '1000000BABYDOGE'),
  ('000bob', 'velo', '1000000BOB'),
  ('000mog', 'velo', '1000000MOG'),
  ('0g', 'velo', '0G'),
  ('0why', 'velo', '10000WHY'),
  ('1inch', 'velo', '1INCH'),
  ('2z', 'velo', '2Z'),
  ('4', 'velo', '4'),
  ('42', 'velo', '42'),
  ('a', 'velo', 'A'),
  ('a2z', 'velo', 'A2Z'),
  ('aave', 'velo', 'AAVE'),
  ('ace', 'velo', 'ACE'),
  ('ach', 'velo', 'ACH'),
  ('act', 'velo', 'ACT'),
  ('across', 'velo', 'ACX'),
  ('aergo', 'velo', 'AERGO'),
  ('aero', 'velo', 'AERO'),
  ('aevo', 'velo', 'AEVO'),
  ('agi', 'velo', 'AGI'),
  ('agld', 'velo', 'AGLD'),
  ('agt', 'velo', 'AGT'),
  ('ai', 'velo', 'AI'),
  ('ain', 'velo', 'AIN'),
  ('aio', 'velo', 'AIO'),
  ('aiot', 'velo', 'AIOT'),
  ('aioz', 'velo', 'AIOZ'),
  ('aixbt', 'velo', 'AIXBT'),
  ('ake', 'velo', 'AKE'),
  ('akt', 'velo', 'AKT'),
  ('alch', 'velo', 'ALCH'),
  ('aleo', 'velo', 'ALEO'),
  ('algorand', 'velo', 'ALGO'),
  ('alice', 'velo', 'ALICE'),
  ('all', 'velo', 'ALL'),
  ('allo', 'velo', 'ALLO'),
  ('alpine', 'velo', 'ALPINE'),
  ('altlayer', 'velo', 'ALT'),
  ('anime', 'velo', 'ANIME'),
  ('ankr', 'velo', 'ANKR'),
  ('ape', 'velo', 'APE'),
  ('apex', 'velo', 'APEX'),
  ('api3', 'velo', 'API3'),
  ('apr', 'velo', 'APR'),
  ('aptos', 'velo', 'APT'),
  ('ar', 'velo', 'AR'),
  ('arbitrum', 'velo', 'ARB'),
  ('arc', 'velo', 'ARC'),
  ('aria', 'velo', 'ARIA'),
  ('ark', 'velo', 'ARK'),
  ('arkham', 'velo', 'ARKM'),
  ('arpa', 'velo', 'ARPA'),
  ('asr', 'velo', 'ASR'),
  ('aster', 'velo', 'ASTER'),
  ('astr', 'velo', 'ASTR'),
  ('at', 'velo', 'AT'),
  ('ata', 'velo', 'ATA'),
  ('ath', 'velo', 'ATH'),
  ('avalanche', 'velo', 'AVAX'),
  ('binance-smart-chain', 'velo', 'BNB'),
  ('bitcoin', 'velo', 'BTC'),
  ('bitcoin-cash', 'velo', 'BCH'),
  ('bittensor', 'velo', 'TAO'),
  ('blast', 'velo', 'BLAST'),
  ('bless', 'velo', 'BLESS'),
  ('bluai', 'velo', 'BLUAI'),
  ('blur', 'velo', 'BLUR'),
  ('bmt', 'velo', 'BMT'),
  ('bnt', 'velo', 'BNT'),
  ('bob', 'velo', 'BOB'),
  ('bome', 'velo', 'BOME'),
  ('bonk', 'velo', '1000BONK'),
  ('br', 'velo', 'BR'),
  ('brett', 'velo', 'BRETT'),
  ('brev', 'velo', 'BREV'),
  ('broccoli', 'velo', 'BROCCOLI'),
  ('broccoli714', 'velo', 'BROCCOLI714'),
  ('broccolif3b', 'velo', 'BROCCOLIF3B'),
  ('bsu', 'velo', 'BSU'),
  ('bsv', 'velo', 'BSV'),
  ('btr', 'velo', 'BTR'),
  ('btt', 'velo', '1000BTT'),
  ('bulla', 'velo', 'BULLA'),
  ('c', 'velo', 'C'),
  ('c98', 'velo', 'C98'),
  ('cake', 'velo', 'CAKE'),
  ('cardano', 'velo', 'ADA'),
  ('carv', 'velo', 'CARV'),
  ('cat', 'velo', '1000CAT'),
  ('cati', 'velo', 'CATI'),
  ('cc', 'velo', 'CC'),
  ('celestia', 'velo', 'TIA'),
  ('celo', 'velo', 'CELO'),
  ('celr', 'velo', 'CELR'),
  ('cetus', 'velo', 'CETUS'),
  ('cfx', 'velo', 'CFX'),
  ('chainlink', 'velo', 'LINK'),
  ('cheems', 'velo', '1000CHEEMS'),
  ('cosmos', 'velo', 'ATOM'),
  ('curve', 'velo', 'CRV'),
  ('dam', 'velo', 'DAM'),
  ('dash', 'velo', 'DASH'),
  ('debridge', 'velo', 'DBR'),
  ('deep', 'velo', 'DEEP'),
  ('degen', 'velo', 'DEGEN'),
  ('dego', 'velo', 'DEGO'),
  ('dent', 'velo', 'DENT'),
  ('dexe', 'velo', 'DEXE'),
  ('df', 'velo', 'DF'),
  ('dia', 'velo', 'DIA'),
  ('dodox', 'velo', 'DODOX'),
  ('dog', 'velo', 'DOG'),
  ('dogecoin', 'velo', 'DOGE'),
  ('dogs', 'velo', 'DOGS'),
  ('dolo', 'velo', 'DOLO'),
  ('dood', 'velo', 'DOOD'),
  ('drift', 'velo', 'DRIFT'),
  ('dusk', 'velo', 'DUSK'),
  ('dydx', 'velo', 'DYDX'),
  ('dym', 'velo', 'DYM'),
  ('eden', 'velo', 'EDEN'),
  ('edu', 'velo', 'EDU'),
  ('egld', 'velo', 'EGLD'),
  ('eigenlayer', 'velo', 'EIGEN'),
  ('enj', 'velo', 'ENJ'),
  ('ens', 'velo', 'ENS'),
  ('enso', 'velo', 'ENSO'),
  ('epic', 'velo', 'EPIC'),
  ('ept', 'velo', 'EPT'),
  ('era', 'velo', 'ERA'),
  ('es', 'velo', 'ES'),
  ('esports', 'velo', 'ESPORTS'),
  ('ethbtc', 'velo', 'ETHBTC'),
  ('ethena', 'velo', 'ENA'),
  ('ethereum', 'velo', 'ETH'),
  ('ethereum-classic', 'velo', 'ETC'),
  ('ethfi', 'velo', 'ETHFI'),
  ('ethw', 'velo', 'ETHW'),
  ('eul', 'velo', 'EUL'),
  ('evaa', 'velo', 'EVAA'),
  ('f', 'velo', 'F'),
  ('fartcoin', 'velo', 'FARTCOIN'),
  ('fetch-ai', 'velo', 'FET'),
  ('ff', 'velo', 'FF'),
  ('fhe', 'velo', 'FHE'),
  ('fida', 'velo', 'FIDA'),
  ('filecoin', 'velo', 'FIL'),
  ('fio', 'velo', 'FIO'),
  ('flock', 'velo', 'FLOCK'),
  ('floki', 'velo', '1000FLOKI'),
  ('flow', 'velo', 'FLOW'),
  ('flr', 'velo', 'FLR'),
  ('fluid', 'velo', 'FLUID'),
  ('flux', 'velo', 'FLUX'),
  ('fogo', 'velo', 'FOGO'),
  ('folks', 'velo', 'FOLKS'),
  ('form', 'velo', 'FORM'),
  ('forth', 'velo', 'FORTH'),
  ('frax', 'velo', 'FRAX'),
  ('fun', 'velo', 'FUN'),
  ('g', 'velo', 'G'),
  ('gala', 'velo', 'GALA'),
  ('gas', 'velo', 'GAS'),
  ('ghst', 'velo', 'GHST'),
  ('giga', 'velo', 'GIGA'),
  ('giggle', 'velo', 'GIGGLE'),
  ('glm', 'velo', 'GLM'),
  ('gmt', 'velo', 'GMT'),
  ('gmx', 'velo', 'GMX'),
  ('goat', 'velo', 'GOAT'),
  ('gps', 'velo', 'GPS'),
  ('grass', 'velo', 'GRASS'),
  ('griffain', 'velo', 'GRIFFAIN'),
  ('gtc', 'velo', 'GTC'),
  ('gua', 'velo', 'GUA'),
  ('gun', 'velo', 'GUN'),
  ('h', 'velo', 'H'),
  ('haedal', 'velo', 'HAEDAL'),
  ('hana', 'velo', 'HANA'),
  ('hbar', 'velo', 'HBAR'),
  ('hei', 'velo', 'HEI'),
  ('hemi', 'velo', 'HEMI'),
  ('hft', 'velo', 'HFT'),
  ('high', 'velo', 'HIGH'),
  ('hippo', 'velo', 'HIPPO'),
  ('hive', 'velo', 'HIVE'),
  ('hmstr', 'velo', 'HMSTR'),
  ('helium-network', 'velo', 'HNT'),
  ('holo', 'velo', 'HOLO'),
  ('home', 'velo', 'HOME'),
  ('hook', 'velo', 'HOOK'),
  ('hot', 'velo', 'HOT'),
  ('hpos10i', 'velo', 'HPOS10I'),
  ('huma', 'velo', 'HUMA'),
  ('hyper', 'velo', 'HYPER'),
  ('hyperliquid', 'velo', 'HYPE'),
  ('icnt', 'velo', 'ICNT'),
  ('icx', 'velo', 'ICX'),
  ('id', 'velo', 'ID'),
  ('idol', 'velo', 'IDOL'),
  ('ilv', 'velo', 'ILV'),
  ('imx', 'velo', 'IMX'),
  ('in', 'velo', 'IN'),
  ('init', 'velo', 'INIT'),
  ('injective', 'velo', 'INJ'),
  ('internet-computer', 'velo', 'ICP'),
  ('io', 'velo', 'IO'),
  ('iost', 'velo', 'IOST'),
  ('iota', 'velo', 'IOTA'),
  ('iotx', 'velo', 'IOTX'),
  ('ip', 'velo', 'IP'),
  ('ir', 'velo', 'IR'),
  ('irys', 'velo', 'IRYS'),
  ('jasmy', 'velo', 'JASMY'),
  ('jct', 'velo', 'JCT'),
  ('jellyjelly', 'velo', 'JELLYJELLY'),
  ('joe', 'velo', 'JOE'),
  ('jst', 'velo', 'JST'),
  ('jto', 'velo', 'JTO'),
  ('jupiter', 'velo', 'JUP'),
  ('kaia', 'velo', 'KAIA'),
  ('kaito', 'velo', 'KAITO'),
  ('kas', 'velo', 'KAS'),
  ('kava', 'velo', 'KAVA'),
  ('kernel', 'velo', 'KERNEL'),
  ('kgen', 'velo', 'KGEN'),
  ('kite', 'velo', 'KITE'),
  ('kmno', 'velo', 'KMNO'),
  ('knc', 'velo', 'KNC'),
  ('koma', 'velo', 'KOMA'),
  ('ksm', 'velo', 'KSM'),
  ('la', 'velo', 'LA'),
  ('lab', 'velo', 'LAB'),
  ('layer', 'velo', 'LAYER'),
  ('lido', 'velo', 'LDO'),
  ('light', 'velo', 'LIGHT'),
  ('linea', 'velo', 'LINEA'),
  ('lista', 'velo', 'LISTA'),
  ('lit', 'velo', 'LIT'),
  ('litecoin', 'velo', 'LTC'),
  ('lpt', 'velo', 'LPT'),
  ('lqty', 'velo', 'LQTY'),
  ('lrc', 'velo', 'LRC'),
  ('lsk', 'velo', 'LSK'),
  ('lumia', 'velo', 'LUMIA'),
  ('luna2', 'velo', 'LUNA2'),
  ('lunc', 'velo', '1000LUNC'),
  ('lyn', 'velo', 'LYN'),
  ('m', 'velo', 'M'),
  ('magic', 'velo', 'MAGIC'),
  ('magma', 'velo', 'MAGMA'),
  ('mana', 'velo', 'MANA'),
  ('manta', 'velo', 'MANTA'),
  ('mask', 'velo', 'MASK'),
  ('mav', 'velo', 'MAV'),
  ('mavia', 'velo', 'MAVIA'),
  ('mbox', 'velo', 'MBOX'),
  ('me', 'velo', 'ME'),
  ('melania', 'velo', 'MELANIA'),
  ('meme', 'velo', 'MEME'),
  ('merl', 'velo', 'MERL'),
  ('met', 'velo', 'MET'),
  ('metis', 'velo', 'METIS'),
  ('mew', 'velo', 'MEW'),
  ('mina', 'velo', 'MINA'),
  ('mira', 'velo', 'MIRA'),
  ('mito', 'velo', 'MITO'),
  ('mln', 'velo', 'MLN'),
  ('mmt', 'velo', 'MMT'),
  ('mnt', 'velo', 'MNT'),
  ('moca', 'velo', 'MOCA'),
  ('mon', 'velo', 'MON'),
  ('moodeng', 'velo', 'MOODENG'),
  ('morpho', 'velo', 'MORPHO'),
  ('movement', 'velo', 'MOVE'),
  ('movr', 'velo', 'MOVR'),
  ('mtl', 'velo', 'MTL'),
  ('mubarak', 'velo', 'MUBARAK'),
  ('myx', 'velo', 'MYX'),
  ('naoris', 'velo', 'NAORIS'),
  ('near', 'velo', 'NEAR'),
  ('neiro', 'velo', 'NEIRO'),
  ('neirocto', 'velo', '1000NEIROCTO'),
  ('neo', 'velo', 'NEO'),
  ('newt', 'velo', 'NEWT'),
  ('nfp', 'velo', 'NFP'),
  ('night', 'velo', 'NIGHT'),
  ('nil', 'velo', 'NIL'),
  ('nkn', 'velo', 'NKN'),
  ('nmr', 'velo', 'NMR'),
  ('nom', 'velo', 'NOM'),
  ('not', 'velo', 'NOT'),
  ('ntrn', 'velo', 'NTRN'),
  ('nxpc', 'velo', 'NXPC'),
  ('og', 'velo', 'OG'),
  ('ogn', 'velo', 'OGN'),
  ('okb', 'velo', 'OKB'),
  ('ol', 'velo', 'OL'),
  ('om', 'velo', 'OM'),
  ('on', 'velo', 'ON'),
  ('ondo', 'velo', 'ONDO'),
  ('one', 'velo', 'ONE'),
  ('ong', 'velo', 'ONG'),
  ('ont', 'velo', 'ONT'),
  ('open', 'velo', 'OPEN'),
  ('optimism', 'velo', 'OP'),
  ('orca', 'velo', 'ORCA'),
  ('order', 'velo', 'ORDER'),
  ('ordi', 'velo', 'ORDI'),
  ('oxt', 'velo', 'OXT'),
  ('parti', 'velo', 'PARTI'),
  ('paxg', 'velo', 'PAXG'),
  ('peaq', 'velo', 'PEAQ'),
  ('pendle', 'velo', 'PENDLE'),
  ('pengu', 'velo', 'PENGU'),
  ('people', 'velo', 'PEOPLE'),
  ('pepe', 'velo', '1000PEPE'),
  ('pha', 'velo', 'PHA'),
  ('phb', 'velo', 'PHB'),
  ('pieverse', 'velo', 'PIEVERSE'),
  ('pippin', 'velo', 'PIPPIN'),
  ('pixel', 'velo', 'PIXEL'),
  ('play', 'velo', 'PLAY'),
  ('plume', 'velo', 'PLUME'),
  ('pnut', 'velo', 'PNUT'),
  ('polygon', 'velo', 'POL'),
  ('polkadot', 'velo', 'DOT'),
  ('polyx', 'velo', 'POLYX'),
  ('ponke', 'velo', 'PONKE'),
  ('popcat', 'velo', 'POPCAT'),
  ('portal', 'velo', 'PORTAL'),
  ('power', 'velo', 'POWER'),
  ('powr', 'velo', 'POWR'),
  ('prom', 'velo', 'PROM'),
  ('prompt', 'velo', 'PROMPT'),
  ('prove', 'velo', 'PROVE'),
  ('ptb', 'velo', 'PTB'),
  ('puffer', 'velo', 'PUFFER'),
  ('pump.fun', 'velo', 'PUMP'),
  ('pumpbtc', 'velo', 'PUMPBTC'),
  ('pundix', 'velo', 'PUNDIX'),
  ('pyth', 'velo', 'PYTH'),
  ('q', 'velo', 'Q'),
  ('qnt', 'velo', 'QNT'),
  ('qtum', 'velo', 'QTUM'),
  ('rare', 'velo', 'RARE'),
  ('rats', 'velo', '1000RATS'),
  ('rave', 'velo', 'RAVE'),
  ('rdnt', 'velo', 'RDNT'),
  ('recall', 'velo', 'RECALL'),
  ('red', 'velo', 'RED'),
  ('render', 'velo', 'RENDER'),
  ('resolv', 'velo', 'RESOLV'),
  ('rez', 'velo', 'REZ'),
  ('rif', 'velo', 'RIF'),
  ('ripple', 'velo', 'XRP'),
  ('river', 'velo', 'RIVER'),
  ('rlc', 'velo', 'RLC'),
  ('rls', 'velo', 'RLS'),
  ('roam', 'velo', 'ROAM'),
  ('ronin', 'velo', 'RONIN'),
  ('rose', 'velo', 'ROSE'),
  ('rpl', 'velo', 'RPL'),
  ('rsr', 'velo', 'RSR'),
  ('rune', 'velo', 'RUNE'),
  ('rvn', 'velo', 'RVN'),
  ('s', 'velo', 'S'),
  ('safe', 'velo', 'SAFE'),
  ('saga', 'velo', 'SAGA'),
  ('sahara', 'velo', 'SAHARA'),
  ('sand', 'velo', 'SAND'),
  ('santos', 'velo', 'SANTOS'),
  ('sapien', 'velo', 'SAPIEN'),
  ('sats', 'velo', '1000SATS'),
  ('sc', 'velo', 'SC'),
  ('scroll', 'velo', 'SCR'),
  ('scrt', 'velo', 'SCRT'),
  ('sei', 'velo', 'SEI'),
  ('sent', 'velo', 'SENT'),
  ('sfp', 'velo', 'SFP'),
  ('shell', 'velo', 'SHELL'),
  ('shib', 'velo', '1000SHIB'),
  ('sign', 'velo', 'SIGN'),
  ('siren', 'velo', 'SIREN'),
  ('skl', 'velo', 'SKL'),
  ('sky', 'velo', 'SKY'),
  ('skyai', 'velo', 'SKYAI'),
  ('slp', 'velo', 'SLP'),
  ('snt', 'velo', 'SNT'),
  ('solana', 'velo', 'SOL'),
  ('solv', 'velo', 'SOLV'),
  ('somi', 'velo', 'SOMI'),
  ('sonic', 'velo', 'SONIC'),
  ('soon', 'velo', 'SOON'),
  ('soph', 'velo', 'SOPH'),
  ('soso', 'velo', 'SOSO'),
  ('spell', 'velo', 'SPELL'),
  ('spk', 'velo', 'SPK'),
  ('sportfun', 'velo', 'SPORTFUN'),
  ('spx', 'velo', 'SPX'),
  ('sqd', 'velo', 'SQD'),
  ('ssv', 'velo', 'SSV'),
  ('stable', 'velo', 'STABLE'),
  ('starknet', 'velo', 'STRK'),
  ('stbl', 'velo', 'STBL'),
  ('steem', 'velo', 'STEEM'),
  ('stg', 'velo', 'STG'),
  ('sto', 'velo', 'STO'),
  ('storj', 'velo', 'STORJ'),
  ('stx', 'velo', 'STX'),
  ('sui', 'velo', 'SUI'),
  ('sun', 'velo', 'SUN'),
  ('super', 'velo', 'SUPER'),
  ('sushiswap', 'velo', 'SUSHI'),
  ('swarms', 'velo', 'SWARMS'),
  ('sxp', 'velo', 'SXP'),
  ('sxt', 'velo', 'SXT'),
  ('syn', 'velo', 'SYN'),
  ('synthetix', 'velo', 'SNX'),
  ('syrup', 'velo', 'SYRUP'),
  ('sys', 'velo', 'SYS'),
  ('t', 'velo', 'T'),
  ('ta', 'velo', 'TA'),
  ('tac', 'velo', 'TAC'),
  ('tag', 'velo', 'TAG'),
  ('taiko', 'velo', 'TAIKO'),
  ('take', 'velo', 'TAKE'),
  ('tanssi', 'velo', 'TANSSI'),
  ('the', 'velo', 'THE'),
  ('the-graph', 'velo', 'GRT'),
  ('theta', 'velo', 'THETA'),
  ('tlm', 'velo', 'TLM'),
  ('tnsr', 'velo', 'TNSR'),
  ('toncoin', 'velo', 'TON'),
  ('toshi', 'velo', 'TOSHI'),
  ('towns', 'velo', 'TOWNS'),
  ('tradoor', 'velo', 'TRADOOR'),
  ('trb', 'velo', 'TRB'),
  ('tree', 'velo', 'TREE'),
  ('tron', 'velo', 'TRX'),
  ('trufi', 'velo', 'TRU'),
  ('trump', 'velo', 'TRUMP'),
  ('trust', 'velo', 'TRUST'),
  ('truth', 'velo', 'TRUTH'),
  ('tst', 'velo', 'TST'),
  ('turbo', 'velo', '1000TURBO'),
  ('turtle', 'velo', 'TURTLE'),
  ('tut', 'velo', 'TUT'),
  ('twt', 'velo', 'TWT'),
  ('uai', 'velo', 'UAI'),
  ('ub', 'velo', 'UB'),
  ('uma', 'velo', 'UMA'),
  ('uniswap', 'velo', 'UNI'),
  ('us', 'velo', 'US'),
  ('usd1', 'velo', 'USD1'),
  ('usdc', 'velo', 'USDC'),
  ('usde', 'velo', 'USDE'),
  ('useless', 'velo', 'USELESS'),
  ('ustc', 'velo', 'USTC'),
  ('usual', 'velo', 'USUAL'),
  ('vana', 'velo', 'VANA'),
  ('vanry', 'velo', 'VANRY'),
  ('velo', 'velo', 'VELO'),
  ('velodrome', 'velo', 'VELODROME'),
  ('velvet', 'velo', 'VELVET'),
  ('vet', 'velo', 'VET'),
  ('vfy', 'velo', 'VFY'),
  ('vic', 'velo', 'VIC'),
  ('vine', 'velo', 'VINE'),
  ('virtual', 'velo', 'VIRTUAL'),
  ('vtho', 'velo', 'VTHO'),
  ('vvv', 'velo', 'VVV'),
  ('w', 'velo', 'W'),
  ('wal', 'velo', 'WAL'),
  ('waves', 'velo', 'WAVES'),
  ('waxp', 'velo', 'WAXP'),
  ('wct', 'velo', 'WCT'),
  ('wld', 'velo', 'WLD'),
  ('xec', 'velo', '1000XEC'),
  ('aave', 'artemis', 'aave'),
  ('across', 'artemis', 'acx'),
  ('aero', 'artemis', 'aero'),
  ('aevo', 'artemis', 'aevo'),
  ('aioz', 'artemis', 'aioz'),
  ('akt', 'artemis', 'akt'),
  ('aleo', 'artemis', 'aleo'),
  ('algorand', 'artemis', 'algo'),
  ('apex', 'artemis', 'apex'),
  ('aptos', 'artemis', 'apt'),
  ('ar', 'artemis', 'ar'),
  ('arbitrum', 'artemis', 'arb'),
  ('aster', 'artemis', 'aster'),
  ('astr', 'artemis', 'astr'),
  ('ath', 'artemis', 'ath'),
  ('avalanche', 'artemis', 'avax'),
  ('binance-smart-chain', 'artemis', 'bnb'),
  ('bitcoin', 'artemis', 'btc'),
  ('bitcoin-cash', 'artemis', 'bch'),
  ('bittensor', 'artemis', 'tao'),
  ('blast', 'artemis', 'blast'),
  ('blur', 'artemis', 'blur'),
  ('bob', 'artemis', 'bob'),
  ('bonk', 'artemis', 'bonk'),
  ('brett', 'artemis', 'brett'),
  ('btt', 'artemis', 'btt'),
  ('cake', 'artemis', 'cake'),
  ('cardano', 'artemis', 'ada'),
  ('celestia', 'artemis', 'tia'),
  ('celo', 'artemis', 'celo'),
  ('cetus', 'artemis', 'cetus'),
  ('cfx', 'artemis', 'cfx'),
  ('chainlink', 'artemis', 'link'),
  ('cosmos', 'artemis', 'atom'),
  ('curve', 'artemis', 'crv'),
  ('deep', 'artemis', 'deep'),
  ('dogecoin', 'artemis', 'doge'),
  ('drift', 'artemis', 'drift'),
  ('dydx', 'artemis', 'dydx'),
  ('egld', 'artemis', 'egld'),
  ('eigenlayer', 'artemis', 'eigen'),
  ('ethena', 'artemis', 'ena'),
  ('ethereum', 'artemis', 'eth'),
  ('ethereum-classic', 'artemis', 'etc'),
  ('ethfi', 'artemis', 'ethfi'),
  ('eul', 'artemis', 'eul'),
  ('fartcoin', 'artemis', 'fartcoin'),
  ('fetch-ai', 'artemis', 'fet'),
  ('filecoin', 'artemis', 'fil'),
  ('floki', 'artemis', 'floki'),
  ('flow', 'artemis', 'flow'),
  ('flr', 'artemis', 'flr'),
  ('fluid', 'artemis', 'fluid'),
  ('gmx', 'artemis', 'gmx'),
  ('grass', 'artemis', 'grass'),
  ('hbar', 'artemis', 'hbar'),
  ('hyperliquid', 'artemis', 'hype'),
  ('injective', 'artemis', 'inj'),
  ('internet-computer', 'artemis', 'icp'),
  ('iotx', 'artemis', 'iotx'),
  ('ip', 'artemis', 'ip'),
  ('joe', 'artemis', 'joe'),
  ('jto', 'artemis', 'jto'),
  ('jupiter', 'artemis', 'jup'),
  ('kava', 'artemis', 'kava'),
  ('kmno', 'artemis', 'kmno'),
  ('layer', 'artemis', 'layer'),
  ('lido', 'artemis', 'ldo'),
  ('light', 'artemis', 'light'),
  ('linea', 'artemis', 'linea'),
  ('litecoin', 'artemis', 'ltc'),
  ('lpt', 'artemis', 'lpt'),
  ('lqty', 'artemis', 'lqty'),
  ('lsk', 'artemis', 'lsk'),
  ('lunc', 'artemis', 'lunc'),
  ('manta', 'artemis', 'manta'),
  ('met', 'artemis', 'met'),
  ('metis', 'artemis', 'metis'),
  ('mnt', 'artemis', 'mnt'),
  ('mon', 'artemis', 'mon'),
  ('morpho', 'artemis', 'morpho'),
  ('movr', 'artemis', 'movr'),
  ('near', 'artemis', 'near'),
  ('neo', 'artemis', 'neo'),
  ('okb', 'artemis', 'okb'),
  ('ondo', 'artemis', 'ondo'),
  ('optimism', 'artemis', 'op'),
  ('orca', 'artemis', 'orca'),
  ('paxg', 'artemis', 'paxg'),
  ('pendle', 'artemis', 'pendle'),
  ('pengu', 'artemis', 'pengu'),
  ('pepe', 'artemis', 'pepe'),
  ('plume', 'artemis', 'plume'),
  ('polygon', 'artemis', 'pol'),
  ('polkadot', 'artemis', 'dot'),
  ('pyth', 'artemis', 'pyth'),
  ('red', 'artemis', 'red'),
  ('render', 'artemis', 'render'),
  ('ripple', 'artemis', 'xrp'),
  ('rose', 'artemis', 'rose'),
  ('rpl', 'artemis', 'rpl'),
  ('rsr', 'artemis', 'rsr'),
  ('s', 'artemis', 's'),
  ('safe', 'artemis', 'safe'),
  ('sei', 'artemis', 'sei'),
  ('shib', 'artemis', 'shib'),
  ('sky', 'artemis', 'sky'),
  ('solana', 'artemis', 'sol'),
  ('spk', 'artemis', 'spk'),
  ('starknet', 'artemis', 'strk'),
  ('stg', 'artemis', 'stg'),
  ('stx', 'artemis', 'stx'),
  ('sui', 'artemis', 'sui'),
  ('synthetix', 'artemis', 'snx'),
  ('syrup', 'artemis', 'syrup'),
  ('the-graph', 'artemis', 'grt'),
  ('toncoin', 'artemis', 'ton'),
  ('tron', 'artemis', 'trx'),
  ('turbo', 'artemis', 'turbo'),
  ('uniswap', 'artemis', 'uni'),
  ('usd1', 'artemis', 'usd1'),
  ('usdc', 'artemis', 'usdc'),
  ('usde', 'artemis', 'usde'),
  ('usual', 'artemis', 'usual'),
  ('vet', 'artemis', 'vet'),
  ('virtual', 'artemis', 'virtual'),
  ('w', 'artemis', 'w'),
  ('wal', 'artemis', 'wal'),
  ('wld', 'artemis', 'wld'),
  ('xec', 'artemis', 'xec'),
  ('aave', 'defillama', 'aave'),
  ('algorand', 'defillama', 'algorand'),
  ('ankr', 'defillama', 'ankr'),
  ('aptos', 'defillama', 'aptos'),
  ('arbitrum', 'defillama', 'arbitrum'),
  ('avalanche', 'defillama', 'avalanche'),
  ('binance-smart-chain', 'defillama', 'bsc'),
  ('bitcoin', 'defillama', 'bitcoin'),
  ('cosmos', 'defillama', 'cosmos'),
  ('curve', 'defillama', 'curve-dex'),
  ('dogecoin', 'defillama', 'doge'),
  ('dydx', 'defillama', 'dydx'),
  ('eigenlayer', 'defillama', 'eigencloud'),
  ('ethena', 'defillama', 'ethena'),
  ('ethereum', 'defillama', 'ethereum'),
  ('filecoin', 'defillama', 'filecoin'),
  ('gala', 'defillama', 'gala'),
  ('gmx', 'defillama', 'gmx'),
  ('hyperliquid', 'defillama', 'hyperliquid-l1'),
  ('injective', 'defillama', 'injective'),
  ('iota', 'defillama', 'iota'),
  ('jupiter', 'defillama', 'jupiter'),
  ('kaia', 'defillama', 'kaia'),
  ('lido', 'defillama', 'lido'),
  ('litecoin', 'defillama', 'litecoin'),
  ('near', 'defillama', 'near'),
  ('optimism', 'defillama', 'optimism'),
  ('pendle', 'defillama', 'pendle'),
  ('polkadot', 'defillama', 'polkadot'),
  ('portal', 'defillama', 'portal'),
  ('pumpbtc', 'defillama', 'pumpbtc'),
  ('resolv', 'defillama', 'resolv'),
  ('ronin', 'defillama', 'ronin'),
  ('saga', 'defillama', 'saga'),
  ('sei', 'defillama', 'sei'),
  ('solana', 'defillama', 'solana'),
  ('sonic', 'defillama', 'sonic'),
  ('starknet', 'defillama', 'starknet'),
  ('sui', 'defillama', 'sui'),
  ('synthetix', 'defillama', 'synthetix'),
  ('tron', 'defillama', 'tron'),
  ('uniswap', 'defillama', 'uniswap'),
  ('waves', 'defillama', 'waves'),
  ('avantis', 'artemis', 'avantis'),
  ('baby', 'artemis', 'baby'),
  ('backed-finance', 'artemis', 'backed-finance'),
  ('bal', 'artemis', 'bal'),
  ('banana', 'artemis', 'banana'),
  ('bonkbot', 'artemis', 'bonkbot'),
  ('cards', 'artemis', 'cards'),
  ('comp', 'artemis', 'comp'),
  ('cvx', 'artemis', 'cvx'),
  ('dflow', 'artemis', 'dflow'),
  ('edgex', 'artemis', 'edgex'),
  ('extended', 'artemis', 'extended'),
  ('falcon-finance', 'artemis', 'falcon_finance'),
  ('felix', 'artemis', 'felix'),
  ('footballdotfun', 'artemis', 'footballdotfun'),
  ('fxs', 'artemis', 'fxs'),
  ('geod', 'artemis', 'geod'),
  ('gns', 'artemis', 'gns'),
  ('hyena', 'artemis', 'hyena'),
  ('hyperlend', 'artemis', 'hyperlend'),
  ('kalshi', 'artemis', 'kalshi'),
  ('kinetiq-markets', 'artemis', 'kinetiq_markets'),
  ('kntq', 'artemis', 'kntq'),
  ('letsbonk', 'artemis', 'letsbonk'),
  ('lighter', 'artemis', 'lighter'),
  ('limitless', 'artemis', 'limitless'),
  ('m0', 'artemis', 'm0'),
  ('mnde', 'artemis', 'mnde'),
  ('momentum', 'artemis', 'momentum'),
  ('opinion', 'artemis', 'opinion'),
  ('ostium', 'artemis', 'ostium'),
  ('paradex', 'artemis', 'paradex'),
  ('polymarket', 'artemis', 'polymarket'),
  ('qi', 'artemis', 'qi'),
  ('rain', 'artemis', 'rain'),
  ('superstate', 'artemis', 'superstate'),
  ('titan', 'artemis', 'titan'),
  ('tradexyz', 'artemis', 'tradexyz'),
  ('trufi', 'artemis', 'trufi'),
  ('ventuals', 'artemis', 'ventuals'),
  ('wet', 'artemis', 'wet'),
  ('xtz', 'artemis', 'xtz'),
  ('xvs', 'artemis', 'xvs'),
  ('zora', 'artemis', 'zora'),
  ('abstract', 'artemis', 'abstract'),
  ('axs', 'artemis', 'axs'),
  ('base', 'artemis', 'base'),
  ('beam', 'artemis', 'beam'),
  ('berachain', 'artemis', 'bera'),
  ('bgb', 'artemis', 'bgb'),
  ('cash', 'artemis', 'cash'),
  ('cro', 'artemis', 'cro'),
  ('frqcy', 'artemis', 'frqcy'),
  ('ftn', 'artemis', 'ftn'),
  ('hash', 'artemis', 'hash'),
  ('hyperevm', 'artemis', 'hyperevm'),
  ('ink', 'artemis', 'ink'),
  ('kcs', 'artemis', 'kcs'),
  ('leo', 'artemis', 'leo'),
  ('luna', 'artemis', 'luna'),
  ('nexo', 'artemis', 'nexo'),
  ('ore', 'artemis', 'ore'),
  ('pi', 'artemis', 'pi'),
  ('ronin', 'artemis', 'ron'),
  ('scroll', 'artemis', 'scroll'),
  ('tel', 'artemis', 'tel'),
  ('unichain', 'artemis', 'unichain'),
  ('wlfi', 'artemis', 'wlfi'),
  ('xcn', 'artemis', 'xcn'),
  ('xdc', 'artemis', 'xdc'),
  ('xlayer', 'artemis', 'xlayer'),
  ('xlm', 'artemis', 'xlm'),
  ('xmr', 'artemis', 'xmr'),
  ('plasma', 'artemis', 'xpl'),
  ('zec', 'artemis', 'zec'),
  ('zk', 'artemis', 'zk'),
  ('binance', 'artemis', 'binance'),
  ('bitstamp', 'artemis', 'bitstamp'),
  ('bybit', 'artemis', 'bybit'),
  ('cryptocom', 'artemis', 'cryptocom'),
  ('gate-io', 'artemis', 'gate_io'),
  ('gemini', 'artemis', 'gemini'),
  ('huobi', 'artemis', 'huobi'),
  ('kraken', 'artemis', 'kraken'),
  ('okx', 'artemis', 'okx'),
  ('eq-abtc', 'artemis', 'eq-abtc'),
  ('eq-asst', 'artemis', 'eq-asst'),
  ('eq-bmnr', 'artemis', 'eq-bmnr'),
  ('eq-bnc', 'artemis', 'eq-bnc'),
  ('eq-btbt', 'artemis', 'eq-btbt'),
  ('eq-btcs', 'artemis', 'eq-btcs'),
  ('eq-cepo', 'artemis', 'eq-cepo'),
  ('eq-chym', 'artemis', 'eq-chym'),
  ('eq-coin', 'artemis', 'eq-coin'),
  ('eq-crcl', 'artemis', 'eq-crcl'),
  ('eq-dave', 'artemis', 'eq-dave'),
  ('eq-dfdv', 'artemis', 'eq-dfdv'),
  ('eq-ethm', 'artemis', 'eq-ethm'),
  ('eq-ethz', 'artemis', 'eq-ethz'),
  ('eq-etor', 'artemis', 'eq-etor'),
  ('eq-fgnx', 'artemis', 'eq-fgnx'),
  ('eq-figr', 'artemis', 'eq-figr'),
  ('eq-ford', 'artemis', 'eq-ford'),
  ('eq-glxy', 'artemis', 'eq-glxy'),
  ('eq-hood', 'artemis', 'eq-hood'),
  ('eq-hsdt', 'artemis', 'eq-hsdt'),
  ('eq-hypd', 'artemis', 'eq-hypd'),
  ('eq-ibkr', 'artemis', 'eq-ibkr'),
  ('eq-mstr', 'artemis', 'eq-mstr'),
  ('eq-mtplf', 'artemis', 'eq-mtplf'),
  ('eq-naka', 'artemis', 'eq-naka'),
  ('eq-nu', 'artemis', 'eq-nu'),
  ('eq-purr', 'artemis', 'eq-purr'),
  ('eq-pypl', 'artemis', 'eq-pypl'),
  ('eq-sata', 'artemis', 'eq-sata'),
  ('eq-sbet', 'artemis', 'eq-sbet'),
  ('eq-schw', 'artemis', 'eq-schw'),
  ('eq-sofi', 'artemis', 'eq-sofi'),
  ('eq-stss', 'artemis', 'eq-stss'),
  ('eq-upxi', 'artemis', 'eq-upxi'),
  ('eq-wt', 'artemis', 'eq-wt'),
  ('eq-xxi', 'artemis', 'eq-xxi'),
  ('eq-xyz', 'artemis', 'eq-xyz'),
  ('nasdaq100', 'artemis', 'nasdaq100'),
  ('strd', 'artemis', 'strd'),
  ('shiba', 'artemis', 'shiba'),
  ('axl', 'artemis', 'axl'),
  ('cctp', 'artemis', 'cctp'),
  ('x402', 'artemis', 'x402'),
  ('buidl', 'artemis', 'buidl'),
  ('wtgxx', 'artemis', 'wtgxx'),
  ('xaut', 'artemis', 'xaut'),
  ('busd', 'artemis', 'busd'),
  ('crvusd', 'artemis', 'crvusd'),
  ('cusd', 'artemis', 'cusd'),
  ('dai', 'artemis', 'dai'),
  ('eura', 'artemis', 'eura'),
  ('eurc', 'artemis', 'eurc'),
  ('eurs', 'artemis', 'eurs'),
  ('fdusd', 'artemis', 'fdusd'),
  ('frxusd', 'artemis', 'frxusd'),
  ('fxusd', 'artemis', 'fxusd'),
  ('gho', 'artemis', 'gho'),
  ('gusd', 'artemis', 'gusd'),
  ('jupusd', 'artemis', 'jupusd'),
  ('lisusd', 'artemis', 'lisusd'),
  ('lusd', 'artemis', 'lusd'),
  ('mim', 'artemis', 'mim'),
  ('pyusd', 'artemis', 'pyusd'),
  ('rlusd', 'artemis', 'rlusd'),
  ('s-usd', 'artemis', 's_usd'),
  ('tusd', 'artemis', 'tusd'),
  ('usd*', 'artemis', 'usd*'),
  ('usd0', 'artemis', 'usd0'),
  ('usda', 'artemis', 'usda'),
  ('usdd', 'artemis', 'usdd'),
  ('usdf', 'artemis', 'usdf'),
  ('usdfalcon', 'artemis', 'usdfalcon'),
  ('usdg', 'artemis', 'usdg'),
  ('usdp', 'artemis', 'usdp'),
  ('usds', 'artemis', 'usds'),
  ('usdt', 'artemis', 'usdt'),
  ('usdt0', 'artemis', 'usdt0'),
  ('usdtb', 'artemis', 'usdtb'),
  ('usdy', 'artemis', 'usdy'),
  ('usdz', 'artemis', 'usdz'),
  ('usn', 'artemis', 'usn'),
  ('usr', 'artemis', 'usr'),
  ('aca', 'artemis', 'aca'),
  ('aeur', 'artemis', 'aeur'),
  ('aftermath', 'artemis', 'aftermath'),
  ('alot', 'artemis', 'alot'),
  ('angle-usd', 'artemis', 'angle_usd'),
  ('bedrock', 'artemis', 'bedrock'),
  ('benji', 'artemis', 'benji'),
  ('black', 'artemis', 'black'),
  ('blue', 'artemis', 'blue'),
  ('bnc', 'artemis', 'bnc'),
  ('bold', 'artemis', 'bold'),
  ('brla', 'artemis', 'brla'),
  ('ceur', 'artemis', 'ceur'),
  ('cfg', 'artemis', 'cfg'),
  ('cgusd', 'artemis', 'cgusd'),
  ('ckes', 'artemis', 'ckes'),
  ('creal', 'artemis', 'creal'),
  ('deusd', 'artemis', 'deusd'),
  ('dimo', 'artemis', 'dimo'),
  ('dodo', 'artemis', 'dodo'),
  ('dola', 'artemis', 'dola'),
  ('egp', 'artemis', 'egp'),
  ('eos', 'artemis', 'eos'),
  ('eurt', 'artemis', 'eurt'),
  ('flexusd', 'artemis', 'flexusd'),
  ('fuse', 'artemis', 'fuse'),
  ('gfi', 'artemis', 'gfi'),
  ('glmr', 'artemis', 'glmr'),
  ('hdx', 'artemis', 'hdx'),
  ('hold', 'artemis', 'hold'),
  ('honey', 'artemis', 'honey'),
  ('idrt', 'artemis', 'idrt'),
  ('idrx', 'artemis', 'idrx'),
  ('intain', 'artemis', 'intain'),
  ('janus', 'artemis', 'janus'),
  ('jewel', 'artemis', 'jewel'),
  ('kar', 'artemis', 'kar'),
  ('kep', 'artemis', 'kep'),
  ('launchcoin', 'artemis', 'launchcoin'),
  ('ll', 'artemis', 'll'),
  ('lvlusd', 'artemis', 'lvlusd'),
  ('mcb', 'artemis', 'mcb'),
  ('mento', 'artemis', 'mento'),
  ('mercado-bitcoin', 'artemis', 'mercado_bitcoin'),
  ('myriadmarket', 'artemis', 'myriadmarket'),
  ('myth', 'artemis', 'myth'),
  ('neon', 'artemis', 'neon'),
  ('neuro', 'artemis', 'neuro'),
  ('pact', 'artemis', 'pact'),
  ('rainbow-bridge', 'artemis', 'rainbow_bridge'),
  ('ref', 'artemis', 'ref'),
  ('saros', 'artemis', 'saros'),
  ('soneium', 'artemis', 'soneium'),
  ('sonne', 'artemis', 'sonne'),
  ('susd', 'artemis', 'susd'),
  ('tradable', 'artemis', 'tradable'),
  ('tryb', 'artemis', 'tryb'),
  ('usd3', 'artemis', 'usd3'),
  ('usdglo', 'artemis', 'usdglo'),
  ('usdx', 'artemis', 'usdx'),
  ('usdxl', 'artemis', 'usdxl'),
  ('xfi', 'artemis', 'xfi'),
  ('zkcro', 'artemis', 'zkcro'),
  ('zrc', 'artemis', 'zrc'),
  ('icpswap', 'defillama', 'icpswap'),
  ('xexchange', 'defillama', 'xexchange'),
  ('t-rize', 'defillama', 't-rize'),
  ('bwatch', 'defillama', 'bwatch'),
  ('flexa', 'defillama', 'flexa'),
  ('bifi', 'defillama', 'bifi'),
  ('avantis', 'defillama', 'avantis'),
  ('zyfai', 'defillama', 'zyfai'),
  ('railgun', 'defillama', 'railgun'),
  ('acryptos', 'defillama', 'acryptos'),
  ('indigo', 'defillama', 'indigo'),
  ('kinetic', 'defillama', 'kinetic'),
  ('sushiswap', 'defillama', 'sushiswap'),
  ('superfluid', 'defillama', 'superfluid'),
  ('zircuit', 'defillama', 'zircuit'),
  ('lumenswap', 'defillama', 'lumenswap'),
  ('chainflip', 'defillama', 'chainflip'),
  ('swissborg', 'defillama', 'swissborg'),
  ('gearbox', 'defillama', 'gearbox'),
  ('mansory', 'defillama', 'mansory'),
  ('pnetwork', 'defillama', 'pnetwork'),
  ('hegic', 'defillama', 'hegic'),
  ('tectonic', 'defillama', 'tectonic'),
  ('storm-trade', 'defillama', 'storm-trade'),
  ('stacks', 'defillama', 'stacks'),
  ('enzyme-finance', 'defillama', 'enzyme-finance'),
  ('xdc', 'defillama', 'xdc'),
  ('usual', 'defillama', 'usual'),
  ('gnosis', 'defillama', 'gnosis'),
  ('angle', 'defillama', 'angle'),
  ('flashtrade', 'defillama', 'flashtrade'),
  ('maya-protocol', 'defillama', 'maya-protocol'),
  ('aura', 'defillama', 'aura'),
  ('nexus-mutual', 'defillama', 'nexus-mutual'),
  ('astroport', 'defillama', 'astroport'),
  ('stride', 'defillama', 'stride'),
  ('blazestake', 'defillama', 'blazestake'),
  ('kava-lend', 'defillama', 'kava-lend'),
  ('bitmex', 'defillama', 'bitmex'),
  ('rootstock', 'defillama', 'rootstock'),
  ('icp', 'defillama', 'icp'),
  ('belt-finance', 'defillama', 'belt-finance'),
  ('chainge-finance', 'defillama', 'chainge-finance'),
  ('berachain', 'defillama', 'berachain'),
  ('reserve-protocol', 'defillama', 'reserve-protocol'),
  ('binance-cex', 'defillama', 'binance-cex'),
  ('fraxtal', 'defillama', 'fraxtal'),
  ('bitkub', 'defillama', 'bitkub'),
  ('paxos-gold', 'defillama', 'paxos-gold'),
  ('bonzo-finance', 'defillama', 'bonzo-finance'),
  ('loopring', 'defillama', 'loopring'),
  ('stables-labs-usdx', 'defillama', 'stables-labs-usdx'),
  ('cardano', 'defillama', 'cardano'),
  ('bifrost-network', 'defillama', 'bifrost-network'),
  ('flokifi-locker', 'defillama', 'flokifi-locker'),
  ('linea', 'defillama', 'linea'),
  ('serum', 'defillama', 'serum'),
  ('metis', 'defillama', 'metis'),
  ('stellar', 'defillama', 'stellar'),
  ('multiversx', 'defillama', 'multiversx'),
  ('rocket-pool', 'defillama', 'rocket-pool'),
  ('aave-v2', 'defillama', 'aave-v2'),
  ('obol', 'defillama', 'obol'),
  ('plume-mainnet', 'defillama', 'plume-mainnet'),
  ('blackrock-buidl', 'defillama', 'blackrock-buidl'),
  ('harvest-finance', 'defillama', 'harvest-finance'),
  ('immutable-zkevm', 'defillama', 'immutable-zkevm'),
  ('x-layer', 'defillama', 'x-layer'),
  ('flare', 'defillama', 'flare'),
  ('zeus-network', 'defillama', 'zeus-network'),
  ('overnight-finance', 'defillama', 'overnight-finance'),
  ('xsy', 'defillama', 'xsy'),
  ('movement', 'defillama', 'movement'),
  ('stake-dao', 'defillama', 'stake-dao'),
  ('gravity-bridge', 'defillama', 'gravity-bridge'),
  ('mento', 'defillama', 'mento'),
  ('coinex', 'defillama', 'coinex'),
  ('synapse', 'defillama', 'synapse'),
  ('orbit-bridge', 'defillama', 'orbit-bridge'),
  ('polygon', 'defillama', 'polygon'),
  ('ichi', 'defillama', 'ichi'),
  ('merlinswap', 'defillama', 'merlinswap'),
  ('looped-hype', 'defillama', 'looped-hype'),
  ('yield-yak-aggregator', 'defillama', 'yield-yak-aggregator'),
  ('osmosis', 'defillama', 'osmosis'),
  ('benqi-lending', 'defillama', 'benqi-lending'),
  ('octus-bridge', 'defillama', 'octus-bridge'),
  ('republic-note', 'defillama', 'republic-note'),
  ('okx', 'defillama', 'okx'),
  ('beefy', 'defillama', 'beefy'),
  ('myx-finance', 'defillama', 'myx-finance'),
  ('xaut', 'defillama', 'tether-gold'),
  ('yield-basis', 'defillama', 'yield-basis'),
  ('pinksale', 'defillama', 'pinksale'),
  ('gravity-by-galxe', 'defillama', 'gravity-by-galxe'),
  ('proxy', 'defillama', 'proxy'),
  ('dolomite', 'defillama', 'dolomite'),
  ('astar', 'defillama', 'astar'),
  ('gains-network', 'defillama', 'gains-network'),
  ('youves', 'defillama', 'youves'),
  ('geth', 'defillama', 'geth'),
  ('morpheusai', 'defillama', 'morpheusai'),
  ('monad', 'defillama', 'monad'),
  ('treehouse-protocol', 'defillama', 'treehouse-protocol'),
  ('index-coop', 'defillama', 'index-coop'),
  ('badger-dao', 'defillama', 'badger-dao'),
  ('blur-bids', 'defillama', 'blur-bids'),
  ('verus', 'defillama', 'verus'),
  ('taiko-bridge', 'defillama', 'taiko-bridge'),
  ('momentum', 'defillama', 'momentum'),
  ('paycash', 'defillama', 'paycash'),
  ('bitkan', 'defillama', 'bitkan'),
  ('mantle', 'defillama', 'mantle'),
  ('plasma', 'defillama', 'plasma'),
  ('connext', 'defillama', 'connext'),
  ('tezos', 'defillama', 'tezos'),
  ('hypha', 'defillama', 'hypha'),
  ('zksync-era', 'defillama', 'zksync-era'),
  ('unirouter', 'defillama', 'unirouter'),
  ('xdai-stake-bridge', 'defillama', 'xdai-stake-bridge'),
  ('vaulta', 'defillama', 'vaulta'),
  ('nexo', 'defillama', 'nexo'),
  ('weex', 'defillama', 'weex'),
  ('yieldnest', 'defillama', 'yieldnest'),
  ('celo', 'defillama', 'celo'),
  ('ston.fi', 'defillama', 'ston.fi'),
  ('debridge', 'defillama', 'debridge'),
  ('justlend', 'defillama', 'justlend'),
  ('dxsale', 'defillama', 'dxsale'),
  ('brickken', 'defillama', 'brickken'),
  ('flow', 'defillama', 'flow'),
  ('realms', 'defillama', 'realms'),
  ('liqwid', 'defillama', 'liqwid'),
  ('metalx-lending', 'defillama', 'metalx-lending'),
  ('manta', 'defillama', 'manta'),
  ('quickswap-dex', 'defillama', 'quickswap-dex'),
  ('alchemix', 'defillama', 'alchemix'),
  ('aquarius-stellar', 'defillama', 'aquarius-stellar'),
  ('beraborrow', 'defillama', 'beraborrow'),
  ('world-chain', 'defillama', 'world-chain'),
  ('amnis-finance', 'defillama', 'amnis-finance'),
  ('idle', 'defillama', 'idle'),
  ('phemex', 'defillama', 'phemex'),
  ('vesper', 'defillama', 'vesper'),
  ('across', 'defillama', 'across'),
  ('linear-protocol', 'defillama', 'linear-protocol'),
  ('minswap', 'defillama', 'minswap'),
  ('kava', 'defillama', 'kava'),
  ('merkle-trade', 'defillama', 'merkle-trade'),
  ('cbridge', 'defillama', 'cbridge'),
  ('hop-protocol', 'defillama', 'hop-protocol'),
  ('origyn', 'defillama', 'origyn'),
  ('nibiru', 'defillama', 'nibiru'),
  ('symmio', 'defillama', 'symmio'),
  ('neo', 'defillama', 'neo'),
  ('blueshift', 'defillama', 'blueshift'),
  ('boson-protocol', 'defillama', 'boson-protocol'),
  ('wombat-exchange', 'defillama', 'wombat-exchange'),
  ('qidao', 'defillama', 'qidao'),
  ('stader', 'defillama', 'stader'),
  ('concentrator', 'defillama', 'concentrator'),
  ('resupply', 'defillama', 'resupply'),
  ('apechain', 'defillama', 'apechain'),
  ('anvil', 'defillama', 'anvil'),
  ('frankencoin', 'defillama', 'frankencoin'),
  ('fantom', 'defillama', 'fantom'),
  ('zerobase-cedefi', 'defillama', 'zerobase-cedefi'),
  ('satlayer', 'defillama', 'satlayer'),
  ('ekubo', 'defillama', 'ekubo'),
  ('ontology', 'defillama', 'ontology'),
  ('babylon-genesis', 'defillama', 'babylon-genesis'),
  ('veno-finance', 'defillama', 'veno-finance'),
  ('powercity-earn-protocol', 'defillama', 'powercity-earn-protocol'),
  ('xpr-network', 'defillama', 'xpr-network'),
  ('wingriders', 'defillama', 'wingriders'),
  ('piku', 'defillama', 'piku'),
  ('aelf', 'defillama', 'aelf'),
  ('penpie', 'defillama', 'penpie'),
  ('iotex', 'defillama', 'iotex'),
  ('harmonix-finance', 'defillama', 'harmonix-finance'),
  ('stusdt', 'defillama', 'stusdt'),
  ('fx-protocol', 'defillama', 'fx-protocol'),
  ('sphere-finance', 'defillama', 'sphere-finance'),
  ('dedust', 'defillama', 'dedust'),
  ('xwin-finance', 'defillama', 'xwin-finance'),
  ('equilibria', 'defillama', 'equilibria'),
  ('wing-finance', 'defillama', 'wing-finance'),
  ('keep3r-network', 'defillama', 'keep3r-network'),
  ('hedera', 'defillama', 'hedera'),
  ('sophon', 'defillama', 'sophon'),
  ('renzo', 'defillama', 'renzo'),
  ('terra2', 'defillama', 'terra2'),
  ('moneyonchain', 'defillama', 'moneyonchain'),
  ('lisk', 'defillama', 'lisk'),
  ('icon', 'defillama', 'icon'),
  ('ethereal', 'defillama', 'ethereal'),
  ('ronin-bridge', 'defillama', 'ronin-bridge'),
  ('equilibre', 'defillama', 'equilibre'),
  ('pulsechain', 'defillama', 'pulsechain'),
  ('gamma', 'defillama', 'gamma'),
  ('xrpl', 'defillama', 'xrpl'),
  ('layerbank', 'defillama', 'layerbank'),
  ('inverse-finance-firm', 'defillama', 'inverse-finance-firm'),
  ('unitus', 'defillama', 'unitus'),
  ('hakka-finance', 'defillama', 'hakka-finance'),
  ('uranium.io', 'defillama', 'uranium.io'),
  ('wemix3.0', 'defillama', 'wemix3.0'),
  ('abc-pool', 'defillama', 'abc-pool'),
  ('deltaprime', 'defillama', 'deltaprime'),
  ('iron-bank', 'defillama', 'iron-bank'),
  ('zigchain', 'defillama', 'zigchain'),
  ('saber', 'defillama', 'saber'),
  ('chiliz', 'defillama', 'chiliz'),
  ('turbos', 'defillama', 'turbos'),
  ('clever', 'defillama', 'clever'),
  ('peapods-finance', 'defillama', 'peapods-finance'),
  ('tornado-cash', 'defillama', 'tornado-cash'),
  ('autofarm', 'defillama', 'autofarm'),
  ('thalaswap', 'defillama', 'thalaswap'),
  ('tinyman', 'defillama', 'tinyman'),
  ('radpie', 'defillama', 'radpie'),
  ('team-finance', 'defillama', 'team-finance'),
  ('conflux', 'defillama', 'conflux'),
  ('hawkfi', 'defillama', 'hawkfi'),
  ('bio-protocol', 'defillama', 'bio-protocol'),
  ('zerolend-lending', 'defillama', 'zerolend-lending'),
  ('probit-global', 'defillama', 'probit-global'),
  ('vires-finance', 'defillama', 'vires-finance'),
  ('map-protocol', 'defillama', 'map-protocol'),
  ('stafi', 'defillama', 'stafi'),
  ('tranchess-yield', 'defillama', 'tranchess-yield'),
  ('splash-protocol', 'defillama', 'splash-protocol'),
  ('cvault-finance', 'defillama', 'cvault-finance'),
  ('toncoin', 'defillama', 'ton'),
  ('ferro', 'defillama', 'ferro'),
  ('bifrost', 'defillama', 'bifrost'),
  ('pickle', 'defillama', 'pickle'),
  ('mixin', 'defillama', 'mixin'),
  ('sdai', 'defillama', 'sdai'),
  ('autofinance', 'defillama', 'autofinance'),
  ('the-idols', 'defillama', 'the-idols'),
  ('hydration', 'defillama', 'hydration'),
  ('meth-protocol', 'defillama', 'meth-protocol'),
  ('hamilton-lane-senior-credit-opportunities-securitize-fund', 'defillama', 'hamilton-lane-senior-credit-opportunities-securitize-fund'),
  ('provenance', 'defillama', 'provenance'),
  ('gyroscope-gyd', 'defillama', 'gyroscope-gyd'),
  ('easedefi.org', 'defillama', 'easedefi.org'),
  ('multichain', 'defillama', 'multichain'),
  ('kpk', 'defillama', 'kpk'),
  ('aktionariat', 'defillama', 'aktionariat'),
  ('symbiosis', 'defillama', 'symbiosis'),
  ('mode', 'defillama', 'mode'),
  ('thorchain', 'defillama', 'thorchain'),
  ('waterneuron', 'defillama', 'waterneuron'),
  ('liquidloans', 'defillama', 'liquidloans'),
  ('convex-finance', 'defillama', 'convex-finance'),
  ('alphalend', 'defillama', 'alphalend'),
  ('0x-aggregator', 'defillama', '0x-aggregator'),
  ('agora-dollar', 'defillama', 'agora-dollar'),
  ('altlayer', 'defillama', 'altlayer'),
  ('arkham', 'defillama', 'arkham'),
  ('axie-infinity', 'defillama', 'axie-infinity'),
  ('banana-gun', 'defillama', 'banana-gun'),
  ('basedmarkets', 'defillama', 'basedmarkets'),
  ('beam', 'defillama', 'beam'),
  ('bittensor', 'defillama', 'bittensor'),
  ('celo-dollar', 'defillama', 'celo-dollar'),
  ('celo-euro', 'defillama', 'celo-euro'),
  ('celo-real', 'defillama', 'celo-real'),
  ('chronicle', 'defillama', 'chronicle'),
  ('dai', 'defillama', 'dai'),
  ('falcon-usd', 'defillama', 'falcon-usd'),
  ('fxusd', 'defillama', 'fxusd'),
  ('helium-network', 'defillama', 'helium-network'),
  ('houdini-swap', 'defillama', 'houdini-swap'),
  ('layerzero', 'defillama', 'layerzero'),
  ('magic-internet-money', 'defillama', 'magic-internet-money'),
  ('metadao', 'defillama', 'metadao'),
  ('metaplex', 'defillama', 'metaplex'),
  ('mstable-usd', 'defillama', 'mstable-usd'),
  ('official-trump', 'defillama', 'official-trump'),
  ('olympus-dao', 'defillama', 'olympus-dao'),
  ('ondo-us-dollar-yield', 'defillama', 'ondo-us-dollar-yield'),
  ('op-mainnet', 'defillama', 'op-mainnet'),
  ('pudgy-penguins', 'defillama', 'pudgy-penguins'),
  ('pump.fun', 'defillama', 'pump.fun'),
  ('request-network', 'defillama', 'request-network'),
  ('resolv-usd', 'defillama', 'resolv-usd'),
  ('sky-dollar', 'defillama', 'sky-dollar'),
  ('thorswap', 'defillama', 'thorswap'),
  ('tornado-finance', 'defillama', 'tornado-finance'),
  ('walrus-protocol', 'defillama', 'walrus-protocol'),
  ('across', 'artemis', 'across'),
  ('plasma', 'artemis', 'plasma'),
  ('aero', 'defillama', 'aerodrome-finance'),
  ('aftermath', 'defillama', 'aftermath-finance'),
  ('aevo', 'defillama', 'aevo'),
  ('axl', 'defillama', 'axelar'),
  ('base', 'defillama', 'base'),
  ('blur', 'defillama', 'blur'),
  ('bob', 'defillama', 'bob'),
  ('scroll', 'defillama', 'scroll'),
  ('axl', 'velo', 'AXL'),
  ('berachain', 'velo', 'BERA'),
  ('plasma', 'velo', 'XPL'),
  ('aerodrome-finance', 'defillama', 'aerodrome'),
  ('celestia', 'defillama', 'celestia'),
  ('chainlink', 'defillama', 'chainlink'),
  ('crvusd', 'defillama', 'crvusd'),
  ('cronos', 'defillama', 'cronos'),
  ('dflow', 'defillama', 'dflow'),
  ('ether-fi', 'defillama', 'ether.fi'),
  ('euler', 'defillama', 'euler'),
  ('ink', 'defillama', 'ink'),
  ('infrared', 'defillama', 'infrared'),
  ('jito-governance-token', 'defillama', 'jito'),
  ('kalshi', 'defillama', 'kalshi'),
  ('kamino', 'defillama', 'kamino-lend'),
  ('lighter', 'defillama', 'lighter'),
  ('liquity', 'defillama', 'liquity'),
  ('m0', 'defillama', 'm0'),
  ('ostium', 'defillama', 'ostium'),
  ('paradex', 'defillama', 'paradex'),
  ('safe', 'defillama', 'safe'),
  ('stargate-finance', 'defillama', 'stargate'),
  ('superstate', 'defillama', 'superstate'),
  ('syrup-finance', 'defillama', 'maple-finance'),
  ('the-graph', 'defillama', 'the-graph'),
  ('layerzero', 'velo', 'ZRO')
) AS v(canonical_id, source, source_id)
JOIN entities e ON e.canonical_id = v.canonical_id
ON CONFLICT (source, source_id) DO NOTHING;
